//
//  Test_German.swift
//
//  Created by automatic.py
//

import XCTest

extension String {
    var x: String {
        self.replacingOccurrences(of: Languages.WordSplitter, with: "")
    }
}

final class Test_German: XCTestCase {

    func test_german() {
        let german = Languages().german
        german.capitalisation = true
        XCTAssertEqual(german.read(0).x, "Null")
        XCTAssertEqual(german.read(1).x, "Eins")
        german.capitalisation = false
        XCTAssertEqual(german.read(0).x, "null")
        XCTAssertEqual(german.read(1).x, "eins")
        XCTAssertEqual(german.read(2).x, "zwei")
        XCTAssertEqual(german.read(3).x, "drei")
        XCTAssertEqual(german.read(4).x, "vier")
        XCTAssertEqual(german.read(5).x, "fünf")
        XCTAssertEqual(german.read(6).x, "sechs")
        XCTAssertEqual(german.read(7).x, "sieben")
        XCTAssertEqual(german.read(8).x, "acht")
        XCTAssertEqual(german.read(9).x, "neun")
        XCTAssertEqual(german.read(10).x, "zehn")
        XCTAssertEqual(german.read(11).x, "elf")
        XCTAssertEqual(german.read(12).x, "zwölf")
        XCTAssertEqual(german.read(13).x, "dreizehn")
        XCTAssertEqual(german.read(14).x, "vierzehn")
        XCTAssertEqual(german.read(15).x, "fünfzehn")
        XCTAssertEqual(german.read(16).x, "sechzehn")
        XCTAssertEqual(german.read(17).x, "siebzehn")
        XCTAssertEqual(german.read(18).x, "achtzehn")
        XCTAssertEqual(german.read(19).x, "neunzehn")
        XCTAssertEqual(german.read(20).x, "zwanzig")
        XCTAssertEqual(german.read(21).x, "einundzwanzig")
        XCTAssertEqual(german.read(24).x, "vierundzwanzig")
        XCTAssertEqual(german.read(25).x, "fünfundzwanzig")
        XCTAssertEqual(german.read(27).x, "siebenundzwanzig")
        XCTAssertEqual(german.read(28).x, "achtundzwanzig")
        XCTAssertEqual(german.read(29).x, "neunundzwanzig")
        XCTAssertEqual(german.read(20).x, "zwanzig")
        XCTAssertEqual(german.read(31).x, "einunddreißig")
        XCTAssertEqual(german.read(32).x, "zweiunddreißig")
        XCTAssertEqual(german.read(33).x, "dreiunddreißig")
        XCTAssertEqual(german.read(34).x, "vierunddreißig")
        XCTAssertEqual(german.read(35).x, "fünfunddreißig")
        XCTAssertEqual(german.read(36).x, "sechsunddreißig")
        XCTAssertEqual(german.read(37).x, "siebenunddreißig")
        XCTAssertEqual(german.read(38).x, "achtunddreißig")
        XCTAssertEqual(german.read(39).x, "neununddreißig")
        XCTAssertEqual(german.read(40).x, "vierzig")
        XCTAssertEqual(german.read(41).x, "einundvierzig")
        XCTAssertEqual(german.read(42).x, "zweiundvierzig")
        XCTAssertEqual(german.read(43).x, "dreiundvierzig")
        XCTAssertEqual(german.read(44).x, "vierundvierzig")
        XCTAssertEqual(german.read(45).x, "fünfundvierzig")
        XCTAssertEqual(german.read(46).x, "sechsundvierzig")
        XCTAssertEqual(german.read(47).x, "siebenundvierzig")
        XCTAssertEqual(german.read(48).x, "achtundvierzig")
        XCTAssertEqual(german.read(49).x, "neunundvierzig")
        XCTAssertEqual(german.read(50).x, "fünfzig")
        XCTAssertEqual(german.read(51).x, "einundfünfzig")
        XCTAssertEqual(german.read(52).x, "zweiundfünfzig")
        XCTAssertEqual(german.read(53).x, "dreiundfünfzig")
        XCTAssertEqual(german.read(54).x, "vierundfünfzig")
        XCTAssertEqual(german.read(55).x, "fünfundfünfzig")
        XCTAssertEqual(german.read(56).x, "sechsundfünfzig")
        XCTAssertEqual(german.read(57).x, "siebenundfünfzig")
        XCTAssertEqual(german.read(58).x, "achtundfünfzig")
        XCTAssertEqual(german.read(59).x, "neunundfünfzig")
        XCTAssertEqual(german.read(60).x, "sechzig")
        XCTAssertEqual(german.read(61).x, "einundsechzig")
        XCTAssertEqual(german.read(62).x, "zweiundsechzig")
        XCTAssertEqual(german.read(63).x, "dreiundsechzig")
        XCTAssertEqual(german.read(64).x, "vierundsechzig")
        XCTAssertEqual(german.read(65).x, "fünfundsechzig")
        XCTAssertEqual(german.read(66).x, "sechsundsechzig")
        XCTAssertEqual(german.read(67).x, "siebenundsechzig")
        XCTAssertEqual(german.read(68).x, "achtundsechzig")
        XCTAssertEqual(german.read(69).x, "neunundsechzig")
        XCTAssertEqual(german.read(70).x, "siebzig")
        XCTAssertEqual(german.read(71).x, "einundsiebzig")
        XCTAssertEqual(german.read(72).x, "zweiundsiebzig")
        XCTAssertEqual(german.read(73).x, "dreiundsiebzig")
        XCTAssertEqual(german.read(74).x, "vierundsiebzig")
        XCTAssertEqual(german.read(75).x, "fünfundsiebzig")
        XCTAssertEqual(german.read(76).x, "sechsundsiebzig")
        XCTAssertEqual(german.read(77).x, "siebenundsiebzig")
        XCTAssertEqual(german.read(78).x, "achtundsiebzig")
        XCTAssertEqual(german.read(79).x, "neunundsiebzig")
        XCTAssertEqual(german.read(80).x, "achtzig")
        XCTAssertEqual(german.read(81).x, "einundachtzig")
        XCTAssertEqual(german.read(82).x, "zweiundachtzig")
        XCTAssertEqual(german.read(83).x, "dreiundachtzig")
        XCTAssertEqual(german.read(84).x, "vierundachtzig")
        XCTAssertEqual(german.read(85).x, "fünfundachtzig")
        XCTAssertEqual(german.read(86).x, "sechsundachtzig")
        XCTAssertEqual(german.read(87).x, "siebenundachtzig")
        XCTAssertEqual(german.read(88).x, "achtundachtzig")
        XCTAssertEqual(german.read(89).x, "neunundachtzig")
        XCTAssertEqual(german.read(90).x, "neunzig")
        XCTAssertEqual(german.read(91).x, "einundneunzig")
        XCTAssertEqual(german.read(92).x, "zweiundneunzig")
        XCTAssertEqual(german.read(93).x, "dreiundneunzig")
        XCTAssertEqual(german.read(94).x, "vierundneunzig")
        XCTAssertEqual(german.read(95).x, "fünfundneunzig")
        XCTAssertEqual(german.read(96).x, "sechsundneunzig")
        XCTAssertEqual(german.read(97).x, "siebenundneunzig")
        XCTAssertEqual(german.read(98).x, "achtundneunzig")
        XCTAssertEqual(german.read(99).x, "neunundneunzig")
        XCTAssertEqual(german.read(100).x, "einhundert")
        XCTAssertEqual(german.read(101).x, "einhunderteins")
        XCTAssertEqual(german.read(102).x, "einhundertzwei")
        XCTAssertEqual(german.read(103).x, "einhundertdrei")
        XCTAssertEqual(german.read(104).x, "einhundertvier")
        XCTAssertEqual(german.read(105).x, "einhundertfünf")
        XCTAssertEqual(german.read(106).x, "einhundertsechs")
        XCTAssertEqual(german.read(107).x, "einhundertsieben")
        XCTAssertEqual(german.read(108).x, "einhundertacht")
        XCTAssertEqual(german.read(109).x, "einhundertneun")
        XCTAssertEqual(german.read(110).x, "einhundertzehn")
        XCTAssertEqual(german.read(111).x, "einhundertelf")
        XCTAssertEqual(german.read(112).x, "einhundertzwölf")
        XCTAssertEqual(german.read(113).x, "einhundertdreizehn")
        XCTAssertEqual(german.read(119).x, "einhundertneunzehn")
        XCTAssertEqual(german.read(120).x, "einhundertzwanzig")
        XCTAssertEqual(german.read(121).x, "einhunderteinundzwanzig")
        XCTAssertEqual(german.read(190).x, "einhundertneunzig")
        XCTAssertEqual(german.read(444).x, "vierhundertvierundvierzig")
        XCTAssertEqual(german.read(999).x, "neunhundertneunundneunzig")
        XCTAssertEqual(german.read(1_000).x, "eintausend")
        XCTAssertEqual(german.read(1_001).x, "eintausendeins")
        XCTAssertEqual(german.read(1_005).x, "eintausendfünf")
        XCTAssertEqual(german.read(1_009).x, "eintausendneun")
        XCTAssertEqual(german.read(1_010).x, "eintausendzehn")
        XCTAssertEqual(german.read(1_011).x, "eintausendelf")
        XCTAssertEqual(german.read(1_012).x, "eintausendzwölf")
        XCTAssertEqual(german.read(1_015).x, "eintausendfünfzehn")
        XCTAssertEqual(german.read(1_035).x, "eintausendfünfunddreißig")
        XCTAssertEqual(german.read(1_099).x, "eintausendneunundneunzig")
        XCTAssertEqual(german.read(1_100).x, "eintausendeinhundert")
        XCTAssertEqual(german.read(1_101).x, "eintausendeinhunderteins")
        XCTAssertEqual(german.read(1_105).x, "eintausendeinhundertfünf")
        XCTAssertEqual(german.read(1_110).x, "eintausendeinhundertzehn")
        XCTAssertEqual(german.read(1_111).x, "eintausendeinhundertelf")
        XCTAssertEqual(german.read(1_115).x, "eintausendeinhundertfünfzehn")
        XCTAssertEqual(german.read(1_121).x, "eintausendeinhunderteinundzwanzig")
        XCTAssertEqual(german.read(1_125).x, "eintausendeinhundertfünfundzwanzig")
        XCTAssertEqual(german.read(10_000).x, "zehntausend")
        XCTAssertEqual(german.read(10_001).x, "zehntausendeins")
        XCTAssertEqual(german.read(20_001).x, "zwanzigtausendeins")
        XCTAssertEqual(german.read(20_010).x, "zwanzigtausendzehn")
        XCTAssertEqual(german.read(20_101).x, "zwanzigtausendeinhunderteins")
        XCTAssertEqual(german.read(201_001).x, "zweihunderteintausendeins")
        XCTAssertEqual(german.read(502_305).x, "fünfhundertzweitausenddreihundertfünf")
        XCTAssertEqual(german.read(999_999).x, "neunhundertneunundneunzigtausendneunhundertneunundneunzig")
        XCTAssertEqual(german.read(62_000_000).x, "zweiundsechzig Millionen")
        XCTAssertEqual(german.read(62_003_005).x, "zweiundsechzig Millionen dreitausendfünf")
        XCTAssertEqual(german.read(62_003_105).x, "zweiundsechzig Millionen dreitausendeinhundertfünf")
        XCTAssertEqual(german.read(62_003_155).x, "zweiundsechzig Millionen dreitausendeinhundertfünfundfünfzig")
        XCTAssertEqual(german.read(99_000_000_909).x, "neunundneunzig Milliarden neunhundertneun")
        XCTAssertEqual(german.read(-1).x, "minus eins")
        XCTAssertEqual(german.read(-15).x, "minus fünfzehn")
        XCTAssertEqual(german.read("1.5").x, "eins Komma fünf")
        XCTAssertEqual(german.read("3.1415926").x, "drei Komma eins vier eins fünf neun zwei sechs")
        XCTAssertEqual(german.read("-3.1415926").x, "minus drei Komma eins vier eins fünf neun zwei sechs")
        XCTAssertEqual(german.read("3.4e13").x, "drei Komma vier mal zehn hoch dreizehn")
        }
}
