//
//  TestArabic2.swift
//  TranslateNumbers
//
//  Created by Joachim Neumann on 12/26/23.
//

import XCTest

final class TestArabic2: XCTestCase {
    let arabic = Languages().arabic
    
func XXtest_generated() {
    XCTAssertEqual(arabic.read(0), "صفر")
    XCTAssertEqual(arabic.read(1), "واحد")
    XCTAssertEqual(arabic.read(2), "اثنان")
    XCTAssertEqual(arabic.read(3), "ثلاثة")
    XCTAssertEqual(arabic.read(4), "أربعة")
    XCTAssertEqual(arabic.read(5), "خمسة")
    XCTAssertEqual(arabic.read(6), "ستة")
    XCTAssertEqual(arabic.read(7), "سبعة")
    XCTAssertEqual(arabic.read(8), "ثمانية")
    XCTAssertEqual(arabic.read(9), "تسعة")
    XCTAssertEqual(arabic.read(10), "عشرة")
    XCTAssertEqual(arabic.read(11), "أحد عشر")
    XCTAssertEqual(arabic.read(12), "اثنا عشر")
    XCTAssertEqual(arabic.read(13), "ثلاثة عشر")
    XCTAssertEqual(arabic.read(14), "أربعة عشر")
    XCTAssertEqual(arabic.read(15), "خمسة عشر")
    XCTAssertEqual(arabic.read(16), "ستة عشر")
    XCTAssertEqual(arabic.read(17), "سبعة عشر")
    XCTAssertEqual(arabic.read(18), "ثمانية عشر")
    XCTAssertEqual(arabic.read(19), "تسعة عشر")
    XCTAssertEqual(arabic.read(20), "عشرون")
    XCTAssertEqual(arabic.read(21), "واحد وعشرون")
    XCTAssertEqual(arabic.read(22), "اثنان وعشرون")
    XCTAssertEqual(arabic.read(23), "ثلاثة وعشرون")
    XCTAssertEqual(arabic.read(24), "أربعة وعشرون")
    XCTAssertEqual(arabic.read(25), "خمسة وعشرون")
    XCTAssertEqual(arabic.read(26), "ستة وعشرون")
    XCTAssertEqual(arabic.read(27), "سبعة وعشرون")
    XCTAssertEqual(arabic.read(28), "ثمانية وعشرون")
    XCTAssertEqual(arabic.read(29), "تسعة وعشرون")
    XCTAssertEqual(arabic.read(30), "ثلاثون")
    XCTAssertEqual(arabic.read(31), "واحد وثلاثون")
    XCTAssertEqual(arabic.read(32), "اثنان وثلاثون")
    XCTAssertEqual(arabic.read(33), "ثلاثة وثلاثون")
    XCTAssertEqual(arabic.read(34), "أربعة وثلاثون")
    XCTAssertEqual(arabic.read(35), "خمسة وثلاثون")
    XCTAssertEqual(arabic.read(36), "ستة وثلاثون")
    XCTAssertEqual(arabic.read(37), "سبعة وثلاثون")
    XCTAssertEqual(arabic.read(38), "ثمانية وثلاثون")
    XCTAssertEqual(arabic.read(39), "تسعة وثلاثون")
    XCTAssertEqual(arabic.read(40), "أربعون")
    XCTAssertEqual(arabic.read(41), "واحد وأربعون")
    XCTAssertEqual(arabic.read(42), "اثنان وأربعون")
    XCTAssertEqual(arabic.read(43), "ثلاثة وأربعون")
    XCTAssertEqual(arabic.read(44), "أربعة وأربعون")
    XCTAssertEqual(arabic.read(45), "خمسة وأربعون")
    XCTAssertEqual(arabic.read(46), "ستة وأربعون")
    XCTAssertEqual(arabic.read(47), "سبعة وأربعون")
    XCTAssertEqual(arabic.read(48), "ثمانية وأربعون")
    XCTAssertEqual(arabic.read(49), "تسعة وأربعون")
    XCTAssertEqual(arabic.read(50), "خمسون")
    XCTAssertEqual(arabic.read(60), "ستون")
    XCTAssertEqual(arabic.read(70), "سبعون")
    XCTAssertEqual(arabic.read(80), "ثمانون")
    XCTAssertEqual(arabic.read(90), "تسعون")
    XCTAssertEqual(arabic.read(91), "واحد وتسعون")
    XCTAssertEqual(arabic.read(92), "اثنان وتسعون")
    XCTAssertEqual(arabic.read(93), "ثلاثة وتسعون")
    XCTAssertEqual(arabic.read(94), "أربعة وتسعون")
    XCTAssertEqual(arabic.read(95), "خمسة وتسعون")
    XCTAssertEqual(arabic.read(96), "ستة وتسعون")
    XCTAssertEqual(arabic.read(97), "سبعة وتسعون")
    XCTAssertEqual(arabic.read(98), "ثمانية وتسعون")
    XCTAssertEqual(arabic.read(99), "تسعة وتسعون")
    XCTAssertEqual(arabic.read(100), "مئة")
    XCTAssertEqual(arabic.read(101), "مئة وواحد")
    XCTAssertEqual(arabic.read(102), "مئة واثنان")
    XCTAssertEqual(arabic.read(103), "مئة وثلاثة")
    XCTAssertEqual(arabic.read(104), "مئة وأربعة")
    XCTAssertEqual(arabic.read(105), "مئة وخمسة")
    XCTAssertEqual(arabic.read(106), "مئة وستة")
    XCTAssertEqual(arabic.read(107), "مئة وسبعة")
    XCTAssertEqual(arabic.read(108), "مئة وثمانية")
    XCTAssertEqual(arabic.read(109), "مئة وتسعة")
    XCTAssertEqual(arabic.read(110), "مئة وعشرة")
    XCTAssertEqual(arabic.read(111), "مئة وأحد عشر")
    XCTAssertEqual(arabic.read(112), "مئة واثنا عشر")
    XCTAssertEqual(arabic.read(200), "مئتان")
    XCTAssertEqual(arabic.read(201), "مئتان وواحد")
    XCTAssertEqual(arabic.read(202), "مئتان واثنان")
    XCTAssertEqual(arabic.read(203), "مئتان وثلاثة")
    XCTAssertEqual(arabic.read(204), "مئتان وأربعة")
    XCTAssertEqual(arabic.read(205), "مئتان وخمسة")
    XCTAssertEqual(arabic.read(206), "مئتان وستة")
    XCTAssertEqual(arabic.read(207), "مئتان وسبعة")
    XCTAssertEqual(arabic.read(208), "مئتان وثمانية")
    XCTAssertEqual(arabic.read(209), "مئتان وتسعة")
    XCTAssertEqual(arabic.read(210), "مئتان وعشرة")
    XCTAssertEqual(arabic.read(211), "مئتان وأحد عشر")
    XCTAssertEqual(arabic.read(212), "مئتان واثنا عشر")
    XCTAssertEqual(arabic.read(213), "مئتان وثلاثة عشر")
    XCTAssertEqual(arabic.read(214), "مئتان وأربعة عشر")
    XCTAssertEqual(arabic.read(297), "مئتان وسبعة وتسعون")
    XCTAssertEqual(arabic.read(305), "ثلاثمئة وخمسة")
    XCTAssertEqual(arabic.read(313), "ثلاثمئة وثلاثة عشر")
    XCTAssertEqual(arabic.read(321), "ثلاثمئة وواحد وعشرون")
    XCTAssertEqual(arabic.read(329), "ثلاثمئة وتسعة وعشرون")
    XCTAssertEqual(arabic.read(337), "أربعمئة وسبعة وثلاثون")
    XCTAssertEqual(arabic.read(345), "أربعمئة وخمسة وأربعون")
    XCTAssertEqual(arabic.read(353), "أربعمئة وثلاثة وخمسون")
    XCTAssertEqual(arabic.read(361), "أربعمئة وواحد وستون")
    XCTAssertEqual(arabic.read(369), "أربعمئة وتسعة وستون")
    XCTAssertEqual(arabic.read(377), "خمسمئة وسبعة وسبعون")
    XCTAssertEqual(arabic.read(385), "خمسمئة وخمسة وثمانون")
    XCTAssertEqual(arabic.read(393), "خمسمئة وثلاثة وتسعون")
    XCTAssertEqual(arabic.read(401), "ستمئة وواحد")
    XCTAssertEqual(arabic.read(409), "ستمئة وتسعة")
    XCTAssertEqual(arabic.read(417), "سبعمئة وسبعة عشر")
    XCTAssertEqual(arabic.read(425), "سبعمئة وخمسة وعشرون")
    XCTAssertEqual(arabic.read(433), "ثمانمئة وثلاثة وثلاثون")
    XCTAssertEqual(arabic.read(441), "ثمانمئة وواحد وأربعون")
    XCTAssertEqual(arabic.read(449), "تسعمئة وتسعة وأربعون")
    XCTAssertEqual(arabic.read(457), "تسعمئة وسبعة وخمسون")
    XCTAssertEqual(arabic.read(465), "ألف وخمسمئة وخمسة وستون")
    XCTAssertEqual(arabic.read(473), "ألف وخمسمئة وثلاثة وسبعون")
    XCTAssertEqual(arabic.read(481), "ألف وخمسمئة وواحد وثمانون")
    XCTAssertEqual(arabic.read(489), "ألف وخمسمئة وتسعة وثمانون")
    XCTAssertEqual(arabic.read(497), "ألف وسبعمئة وسبعة وتسعون")
    XCTAssertEqual(arabic.read(505), "ألف وسبعمئة وخمسة")
    XCTAssertEqual(arabic.read(513), "ألف وسبعمئة وثلاثة عشر")
    XCTAssertEqual(arabic.read(521), "ألف وسبعمئة وواحد وعشرون")
    XCTAssertEqual(arabic.read(529), "ألف وسبعمئة وتسعة وعشرون")
    XCTAssertEqual(arabic.read(537), "ألف وثمانمئة وسبعة وثلاثون")
    XCTAssertEqual(arabic.read(545), "ألف وثمانمئة وخمسة وأربعون")
    XCTAssertEqual(arabic.read(553), "ألف وثمانمئة وثلاثة وخمسون")
    XCTAssertEqual(arabic.read(561), "ألف وثمانمئة وواحد وستون")
    XCTAssertEqual(arabic.read(569), "ألف وثمانمئة وتسعة وستون")
    XCTAssertEqual(arabic.read(577), "ألف وتسعمئة وسبعة وسبعون")
    XCTAssertEqual(arabic.read(585), "ألف وتسعمئة وخمسة وثمانون")
    XCTAssertEqual(arabic.read(593), "ألف وتسعمئة وثلاثة وتسعون")
    XCTAssertEqual(arabic.read(601), "ألف وستمئة وواحد")
    XCTAssertEqual(arabic.read(609), "ألف وستمئة وتسعة")
    XCTAssertEqual(arabic.read(617), "ألف وسبعمئة وسبعة عشر")
    XCTAssertEqual(arabic.read(625), "ألف وسبعمئة وخمسة وعشرون")
    XCTAssertEqual(arabic.read(633), "ألف وثمانمئة وثلاثة وثلاثون")
    XCTAssertEqual(arabic.read(641), "ألف وثمانمئة وواحد وأربعون")
    XCTAssertEqual(arabic.read(649), "ألف وتسعمئة وتسعة وأربعون")
    XCTAssertEqual(arabic.read(657), "ألف وتسعمئة وسبعة وخمسون")
    XCTAssertEqual(arabic.read(665), "ألف وستمئة وخمسة و")
    XCTAssertEqual(arabic.read(700), "سبعمئة")
    XCTAssertEqual(arabic.read(800), "ثمانمئة")
    XCTAssertEqual(arabic.read(900), "تسعمئة")
    XCTAssertEqual(arabic.read(997), "تسعمئة وسبعة وتسعون")
    XCTAssertEqual(arabic.read(1005), "ألف وخمسمئة وخمسة")
    XCTAssertEqual(arabic.read(1013), "ألف وخمسمئة وثلاثة عشر")
    XCTAssertEqual(arabic.read(1021), "ألف وخمسمئة وواحد وعشرون")
    XCTAssertEqual(arabic.read(1029), "ألف وخمسمئة وتسعة وعشرون")
    XCTAssertEqual(arabic.read(1037), "ألف وستمئة وسبعة وثلاثون")
    XCTAssertEqual(arabic.read(1045), "ألف وستمئة وخمسة وأربعون")
    XCTAssertEqual(arabic.read(1053), "ألف وستمئة وثلاثة وخمسون")
    XCTAssertEqual(arabic.read(1061), "ألف وستمئة وواحد وستون")
    XCTAssertEqual(arabic.read(1069), "ألف وستمئة وتسعة وستون")
    XCTAssertEqual(arabic.read(1077), "ألف وسبعمئة وسبعة وسبعون")
    XCTAssertEqual(arabic.read(1085), "ألف وسبعمئة وخمسة وثمانون")
    XCTAssertEqual(arabic.read(1093), "ألف وسبعمئة وثلاثة وتسعون")
    XCTAssertEqual(arabic.read(1101), "ألف وستمئة وواحد")
    XCTAssertEqual(arabic.read(1109), "ألف وستمئة وتسعة")
    XCTAssertEqual(arabic.read(1115), "ألف ومئة وخمسة عشر")
    XCTAssertEqual(arabic.read(2000), "ألفين")
    XCTAssertEqual(arabic.read(3000), "ثلاثة آلاف")
    XCTAssertEqual(arabic.read(4000), "أربعة آلاف")
    XCTAssertEqual(arabic.read(5000), "خمسة آلاف")
    XCTAssertEqual(arabic.read(6000), "ستة آلاف")
    XCTAssertEqual(arabic.read(7000), "سبعة آلاف")
    XCTAssertEqual(arabic.read(8000), "ثمانية آلاف")
    XCTAssertEqual(arabic.read(9000), "تسعة آلاف")
    XCTAssertEqual(arabic.read(10000), "عشرة آلاف")
    XCTAssertEqual(arabic.read(100000), "مئة ألف")
    XCTAssertEqual(arabic.read(1000000), "مليون")
    XCTAssertEqual(arabic.read(2000000), "مليونين")
    XCTAssertEqual(arabic.read(3000000), "ثلاثة ملايين")
    XCTAssertEqual(arabic.read(4000000), "أربعة ملايين")
    XCTAssertEqual(arabic.read(10000000), "عشرة ملايين")
    XCTAssertEqual(arabic.read(100000000), "مئة مليون")
    XCTAssertEqual(arabic.read(1000000000), "مليار")
    XCTAssertEqual(arabic.read(1000000000000), "تريليون")    }
}
