//
//  Test_Automatic_German.swift
//
//  Created by automatic.py
//

import XCTest

final class TranslationsTestsAutomaticGerman: XCTestCase {

    func test_german() {
        var german = Languages().german
        german.useWordSplitter = false
        german.capitalisation = true
        XCTAssertEqual(german.read(0), "Null")
        XCTAssertEqual(german.read(1), "Eins")
        german.capitalisation = false
        XCTAssertEqual(german.read(0), "null")
        XCTAssertEqual(german.read(1), "eins")
        XCTAssertEqual(german.read(2), "zwei")
        XCTAssertEqual(german.read(3), "drei")
        XCTAssertEqual(german.read(4), "vier")
        XCTAssertEqual(german.read(5), "fünf")
        XCTAssertEqual(german.read(6), "sechs")
        XCTAssertEqual(german.read(7), "sieben")
        XCTAssertEqual(german.read(8), "acht")
        XCTAssertEqual(german.read(9), "neun")
        XCTAssertEqual(german.read(10), "zehn")
        XCTAssertEqual(german.read(11), "elf")
        XCTAssertEqual(german.read(12), "zwölf")
        XCTAssertEqual(german.read(13), "dreizehn")
        XCTAssertEqual(german.read(14), "vierzehn")
        XCTAssertEqual(german.read(15), "fünfzehn")
        XCTAssertEqual(german.read(16), "sechzehn")
        XCTAssertEqual(german.read(17), "siebzehn")
        XCTAssertEqual(german.read(18), "achtzehn")
        XCTAssertEqual(german.read(19), "neunzehn")
        XCTAssertEqual(german.read(20), "zwanzig")
        XCTAssertEqual(german.read(21), "einundzwanzig")
        XCTAssertEqual(german.read(24), "vierundzwanzig")
        XCTAssertEqual(german.read(25), "fünfundzwanzig")
        XCTAssertEqual(german.read(27), "siebenundzwanzig")
        XCTAssertEqual(german.read(28), "achtundzwanzig")
        XCTAssertEqual(german.read(29), "neunundzwanzig")
        XCTAssertEqual(german.read(20), "zwanzig")
        XCTAssertEqual(german.read(31), "einunddreißig")
        XCTAssertEqual(german.read(32), "zweiunddreißig")
        XCTAssertEqual(german.read(33), "dreiunddreißig")
        XCTAssertEqual(german.read(34), "vierunddreißig")
        XCTAssertEqual(german.read(35), "fünfunddreißig")
        XCTAssertEqual(german.read(36), "sechsunddreißig")
        XCTAssertEqual(german.read(37), "siebenunddreißig")
        XCTAssertEqual(german.read(38), "achtunddreißig")
        XCTAssertEqual(german.read(39), "neununddreißig")
        XCTAssertEqual(german.read(40), "vierzig")
        XCTAssertEqual(german.read(41), "einundvierzig")
        XCTAssertEqual(german.read(42), "zweiundvierzig")
        XCTAssertEqual(german.read(43), "dreiundvierzig")
        XCTAssertEqual(german.read(44), "vierundvierzig")
        XCTAssertEqual(german.read(45), "fünfundvierzig")
        XCTAssertEqual(german.read(46), "sechsundvierzig")
        XCTAssertEqual(german.read(47), "siebenundvierzig")
        XCTAssertEqual(german.read(48), "achtundvierzig")
        XCTAssertEqual(german.read(49), "neunundvierzig")
        XCTAssertEqual(german.read(50), "fünfzig")
        XCTAssertEqual(german.read(51), "einundfünfzig")
        XCTAssertEqual(german.read(52), "zweiundfünfzig")
        XCTAssertEqual(german.read(53), "dreiundfünfzig")
        XCTAssertEqual(german.read(54), "vierundfünfzig")
        XCTAssertEqual(german.read(55), "fünfundfünfzig")
        XCTAssertEqual(german.read(56), "sechsundfünfzig")
        XCTAssertEqual(german.read(57), "siebenundfünfzig")
        XCTAssertEqual(german.read(58), "achtundfünfzig")
        XCTAssertEqual(german.read(59), "neunundfünfzig")
        XCTAssertEqual(german.read(60), "sechzig")
        XCTAssertEqual(german.read(61), "einundsechzig")
        XCTAssertEqual(german.read(62), "zweiundsechzig")
        XCTAssertEqual(german.read(63), "dreiundsechzig")
        XCTAssertEqual(german.read(64), "vierundsechzig")
        XCTAssertEqual(german.read(65), "fünfundsechzig")
        XCTAssertEqual(german.read(66), "sechsundsechzig")
        XCTAssertEqual(german.read(67), "siebenundsechzig")
        XCTAssertEqual(german.read(68), "achtundsechzig")
        XCTAssertEqual(german.read(69), "neunundsechzig")
        XCTAssertEqual(german.read(70), "siebzig")
        XCTAssertEqual(german.read(71), "einundsiebzig")
        XCTAssertEqual(german.read(72), "zweiundsiebzig")
        XCTAssertEqual(german.read(73), "dreiundsiebzig")
        XCTAssertEqual(german.read(74), "vierundsiebzig")
        XCTAssertEqual(german.read(75), "fünfundsiebzig")
        XCTAssertEqual(german.read(76), "sechsundsiebzig")
        XCTAssertEqual(german.read(77), "siebenundsiebzig")
        XCTAssertEqual(german.read(78), "achtundsiebzig")
        XCTAssertEqual(german.read(79), "neunundsiebzig")
        XCTAssertEqual(german.read(80), "achtzig")
        XCTAssertEqual(german.read(81), "einundachtzig")
        XCTAssertEqual(german.read(82), "zweiundachtzig")
        XCTAssertEqual(german.read(83), "dreiundachtzig")
        XCTAssertEqual(german.read(84), "vierundachtzig")
        XCTAssertEqual(german.read(85), "fünfundachtzig")
        XCTAssertEqual(german.read(86), "sechsundachtzig")
        XCTAssertEqual(german.read(87), "siebenundachtzig")
        XCTAssertEqual(german.read(88), "achtundachtzig")
        XCTAssertEqual(german.read(89), "neunundachtzig")
        XCTAssertEqual(german.read(90), "neunzig")
        XCTAssertEqual(german.read(91), "einundneunzig")
        XCTAssertEqual(german.read(92), "zweiundneunzig")
        XCTAssertEqual(german.read(93), "dreiundneunzig")
        XCTAssertEqual(german.read(94), "vierundneunzig")
        XCTAssertEqual(german.read(95), "fünfundneunzig")
        XCTAssertEqual(german.read(96), "sechsundneunzig")
        XCTAssertEqual(german.read(97), "siebenundneunzig")
        XCTAssertEqual(german.read(98), "achtundneunzig")
        XCTAssertEqual(german.read(99), "neunundneunzig")
        XCTAssertEqual(german.read(100), "einhundert")
        XCTAssertEqual(german.read(101), "einhunderteins")
        XCTAssertEqual(german.read(102), "einhundertzwei")
        XCTAssertEqual(german.read(103), "einhundertdrei")
        XCTAssertEqual(german.read(104), "einhundertvier")
        XCTAssertEqual(german.read(105), "einhundertfünf")
        XCTAssertEqual(german.read(106), "einhundertsechs")
        XCTAssertEqual(german.read(107), "einhundertsieben")
        XCTAssertEqual(german.read(108), "einhundertacht")
        XCTAssertEqual(german.read(109), "einhundertneun")
        XCTAssertEqual(german.read(110), "einhundertzehn")
        XCTAssertEqual(german.read(111), "einhundertelf")
        XCTAssertEqual(german.read(112), "einhundertzwölf")
        XCTAssertEqual(german.read(113), "einhundertdreizehn")
        XCTAssertEqual(german.read(119), "einhundertneunzehn")
        XCTAssertEqual(german.read(120), "einhundertzwanzig")
        XCTAssertEqual(german.read(121), "einhunderteinundzwanzig")
        XCTAssertEqual(german.read(190), "einhundertneunzig")
        XCTAssertEqual(german.read(444), "vierhundertvierundvierzig")
        XCTAssertEqual(german.read(999), "neunhundertneunundneunzig")
        XCTAssertEqual(german.read(1_000), "eintausend")
        XCTAssertEqual(german.read(1_001), "eintausendeins")
        XCTAssertEqual(german.read(1_005), "eintausendfünf")
        XCTAssertEqual(german.read(1_009), "eintausendneun")
        XCTAssertEqual(german.read(1_010), "eintausendzehn")
        XCTAssertEqual(german.read(1_011), "eintausendelf")
        XCTAssertEqual(german.read(1_012), "eintausendzwölf")
        XCTAssertEqual(german.read(1_015), "eintausendfünfzehn")
        XCTAssertEqual(german.read(1_035), "eintausendfünfunddreißig")
        XCTAssertEqual(german.read(1_099), "eintausendneunundneunzig")
        XCTAssertEqual(german.read(1_100), "eintausendeinhundert")
        XCTAssertEqual(german.read(1_101), "eintausendeinhunderteins")
        XCTAssertEqual(german.read(1_105), "eintausendeinhundertfünf")
        XCTAssertEqual(german.read(1_110), "eintausendeinhundertzehn")
        XCTAssertEqual(german.read(1_111), "eintausendeinhundertelf")
        XCTAssertEqual(german.read(1_115), "eintausendeinhundertfünfzehn")
        XCTAssertEqual(german.read(1_121), "eintausendeinhunderteinundzwanzig")
        XCTAssertEqual(german.read(1_125), "eintausendeinhundertfünfundzwanzig")
        XCTAssertEqual(german.read(10_000), "zehntausend")
        XCTAssertEqual(german.read(10_001), "zehntausendeins")
        XCTAssertEqual(german.read(20_001), "zwanzigtausendeins")
        XCTAssertEqual(german.read(20_010), "zwanzigtausendzehn")
        XCTAssertEqual(german.read(20_101), "zwanzigtausendeinhunderteins")
        XCTAssertEqual(german.read(201_001), "zweihunderteintausendeins")
        XCTAssertEqual(german.read(502_305), "fünfhundertzweitausenddreihundertfünf")
        XCTAssertEqual(german.read(999_999), "neunhundertneunundneunzigtausendneunhundertneunundneunzig")
        XCTAssertEqual(german.read(62_000_000), "zweiundsechzig Millionen")
        XCTAssertEqual(german.read(62_003_005), "zweiundsechzig Millionen dreitausendfünf")
        XCTAssertEqual(german.read(62_003_105), "zweiundsechzig Millionen dreitausendeinhundertfünf")
        XCTAssertEqual(german.read(62_003_155), "zweiundsechzig Millionen dreitausendeinhundertfünfundfünfzig")
        XCTAssertEqual(german.read(99_000_000_909), "neunundneunzig Milliarden neunhundertneun")
        XCTAssertEqual(german.read(-1), "minus eins")
        XCTAssertEqual(german.read(-15), "minus fünfzehn")
        XCTAssertEqual(german.read("1.5"), "eins Komma fünf")
        XCTAssertEqual(german.read("3.1415926"), "drei Komma eins vier eins fünf neun zwei sechs")
        XCTAssertEqual(german.read("-3.1415926"), "minus drei Komma eins vier eins fünf neun zwei sechs")
        XCTAssertEqual(german.read("3.4e13"), "drei Komma vier mal zehn hoch dreizehn")
        }
}
