//
//  TestArabic.swift
//  TranslateNumbersTests
//
//  Created by Joachim Neumann on 12/25/23.
//

import XCTest

final class TestArabic: XCTestCase {
    let arabic = Languages().arabic
    
    func XXtest() {
        /// https://lexisrex.com/Arabic-Numbers/1-1000
        XCTAssertEqual(arabic.read(0), "صفر")
        XCTAssertEqual(arabic.read(1), "وَاحِد")
        XCTAssertEqual(arabic.read(2), "اِثْنَان")
        XCTAssertEqual(arabic.read(3), "ثَلَاثَة")
        XCTAssertEqual(arabic.read(4), "أَرْبَعَة")
        XCTAssertEqual(arabic.read(5), "خَمْسَة")
        XCTAssertEqual(arabic.read(6), "سِتَّة")
        XCTAssertEqual(arabic.read(7), "سَبْعَة")
        XCTAssertEqual(arabic.read(8), "ثَمَانِيَة")
        XCTAssertEqual(arabic.read(9), "تِسْعَة")
        XCTAssertEqual(arabic.read(10), "عَشَرَة")
        XCTAssertEqual(arabic.read(11), "أَحَدَ عَشَرَ")
        XCTAssertEqual(arabic.read(12), "اِثْنَا عَشَرَ")
        XCTAssertEqual(arabic.read(13), "ثَلَاثَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(14), "أَرْبَعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(15), "خَمْسَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(16), "سِتَّةَ عَشَرَ")
        XCTAssertEqual(arabic.read(17), "سَبْعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(18), "ثَمَانِيَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(19), "تِسْعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(20), "عِشْرُونَ")
        XCTAssertEqual(arabic.read(21), "وَاحِد و عِشْرُونَ")
        XCTAssertEqual(arabic.read(22), "اِثْنَان و عِشْرُونَ")
        XCTAssertEqual(arabic.read(23), "ثَلَاثَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(24), "أَرْبَعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(25), "خَمْسَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(26), "سِتَّة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(27), "سَبْعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(28), "ثَمَانِيَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(29), "تِسْعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(30), "ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(31), "وَاحِد و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(32), "اِثْنَان و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(33), "ثَلَاثَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(34), "أَرْبَعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(35), "خَمْسَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(36), "سِتَّة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(37), "سَبْعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(38), "ثَمَانِيَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(39), "تِسْعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(40), "أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(41), "وَاحِد و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(42), "اِثْنَان و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(43), "ثَلَاثَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(44), "أَرْبَعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(45), "خَمْسَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(46), "سِتَّة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(47), "سَبْعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(48), "ثَمَانِيَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(49), "تِسْعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(50), "خَمْسُونَ")
        XCTAssertEqual(arabic.read(51), "وَاحِد و خَمْسُونَ")
        XCTAssertEqual(arabic.read(52), "اِثْنَان و خَمْسُونَ")
        XCTAssertEqual(arabic.read(53), "ثَلَاثَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(54), "أَرْبَعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(55), "خَمْسَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(56), "سِتَّة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(57), "سَبْعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(58), "ثَمَانِيَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(59), "تِسْعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(60), "سِتُّونَ")
        XCTAssertEqual(arabic.read(61), "وَاحِد و سِتُّونَ")
        XCTAssertEqual(arabic.read(62), "اِثْنَان و سِتُّونَ")
        XCTAssertEqual(arabic.read(63), "ثَلَاثَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(64), "أَرْبَعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(65), "خَمْسَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(66), "سِتَّة و سِتُّونَ")
        XCTAssertEqual(arabic.read(67), "سَبْعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(68), "ثَمَانِيَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(69), "تِسْعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(70), "سَبْعُونَ")
        XCTAssertEqual(arabic.read(71), "وَاحِد و سَبْعُونَ")
        XCTAssertEqual(arabic.read(72), "اِثْنَان و سَبْعُونَ")
        XCTAssertEqual(arabic.read(73), "ثَلَاثَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(74), "أَرْبَعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(75), "خَمْسَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(76), "سِتَّة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(77), "سَبْعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(78), "ثَمَانِيَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(79), "تِسْعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(80), "ثَمَانُونَ")
        XCTAssertEqual(arabic.read(81), "وَاحِد و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(82), "اِثْنَان و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(83), "ثَلَاثَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(84), "أَرْبَعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(85), "خَمْسَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(86), "سِتَّة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(87), "سَبْعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(88), "ثَمَانِيَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(89), "تِسْعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(90), "تِسْعُونَ")
        XCTAssertEqual(arabic.read(91), "وَاحِد و تِسْعُونَ")
        XCTAssertEqual(arabic.read(92), "اِثْنَان و تِسْعُونَ")
        XCTAssertEqual(arabic.read(93), "ثَلَاثَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(94), "أَرْبَعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(95), "خَمْسَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(96), "سِتَّة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(97), "سَبْعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(98), "ثَمَانِيَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(99), "تِسْعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(100), "مِئَة")
        XCTAssertEqual(arabic.read(101), "مِئَة و وَاحِد")
        XCTAssertEqual(arabic.read(102), "مِئَة و اِثْنَان")
        XCTAssertEqual(arabic.read(103), "مِئَة و ثَلَاثَة")
        XCTAssertEqual(arabic.read(104), "مِئَة و أَرْبَعَة")
        XCTAssertEqual(arabic.read(105), "مِئَة و خَمْسَة")
        XCTAssertEqual(arabic.read(106), "مِئَة و سِتَّة")
        XCTAssertEqual(arabic.read(107), "مِئَة و سَبْعَة")
        XCTAssertEqual(arabic.read(108), "مِئَة و ثَمَانِيَة")
        XCTAssertEqual(arabic.read(109), "مِئَة و تِسْعَة")
        XCTAssertEqual(arabic.read(110), "مِئَة و عَشَرَة")
        XCTAssertEqual(arabic.read(111), "مِئَة و أَحَدَ عَشَرَ")
        XCTAssertEqual(arabic.read(112), "مِئَة و اِثْنَا عَشَرَ")
        XCTAssertEqual(arabic.read(113), "مِئَة و ثَلَاثَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(114), "مِئَة و أَرْبَعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(115), "مِئَة و خَمْسَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(116), "مِئَة و سِتَّةَ عَشَرَ")
        XCTAssertEqual(arabic.read(117), "مِئَة و سَبْعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(118), "مِئَة و ثَمَانِيَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(119), "مِئَة و تِسْعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(120), "مِئَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(121), "مِئَة و وَاحِد و عِشْرُونَ")
        XCTAssertEqual(arabic.read(122), "مِئَة و اِثْنَان و عِشْرُونَ")
        XCTAssertEqual(arabic.read(123), "مِئَة و ثَلَاثَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(124), "مِئَة و أَرْبَعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(125), "مِئَة و خَمْسَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(126), "مِئَة و سِتَّة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(127), "مِئَة و سَبْعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(128), "مِئَة و ثَمَانِيَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(129), "مِئَة و تِسْعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(130), "مِئَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(131), "مِئَة و وَاحِد و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(132), "مِئَة و اِثْنَان و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(133), "مِئَة و ثَلَاثَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(134), "مِئَة و أَرْبَعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(135), "مِئَة و خَمْسَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(136), "مِئَة و سِتَّة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(137), "مِئَة و سَبْعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(138), "مِئَة و ثَمَانِيَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(139), "مِئَة و تِسْعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(140), "مِئَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(141), "مِئَة و وَاحِد و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(142), "مِئَة و اِثْنَان و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(143), "مِئَة و ثَلَاثَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(144), "مِئَة و أَرْبَعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(145), "مِئَة و خَمْسَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(146), "مِئَة و سِتَّة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(147), "مِئَة و سَبْعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(148), "مِئَة و ثَمَانِيَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(149), "مِئَة و تِسْعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(150), "مِئَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(151), "مِئَة و وَاحِد و خَمْسُونَ")
        XCTAssertEqual(arabic.read(152), "مِئَة و اِثْنَان و خَمْسُونَ")
        XCTAssertEqual(arabic.read(153), "مِئَة و ثَلَاثَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(154), "مِئَة و أَرْبَعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(155), "مِئَة و خَمْسَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(156), "مِئَة و سِتَّة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(157), "مِئَة و سَبْعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(158), "مِئَة و ثَمَانِيَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(159), "مِئَة و تِسْعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(160), "مِئَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(161), "مِئَة و وَاحِد و سِتُّونَ")
        XCTAssertEqual(arabic.read(162), "مِئَة و اِثْنَان و سِتُّونَ")
        XCTAssertEqual(arabic.read(163), "مِئَة و ثَلَاثَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(164), "مِئَة و أَرْبَعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(165), "مِئَة و خَمْسَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(166), "مِئَة و سِتَّة و سِتُّونَ")
        XCTAssertEqual(arabic.read(167), "مِئَة و سَبْعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(168), "مِئَة و ثَمَانِيَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(169), "مِئَة و تِسْعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(170), "مِئَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(171), "مِئَة و وَاحِد و سَبْعُونَ")
        XCTAssertEqual(arabic.read(172), "مِئَة و اِثْنَان و سَبْعُونَ")
        XCTAssertEqual(arabic.read(173), "مِئَة و ثَلَاثَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(174), "مِئَة و أَرْبَعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(175), "مِئَة و خَمْسَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(176), "مِئَة و سِتَّة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(177), "مِئَة و سَبْعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(178), "مِئَة و ثَمَانِيَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(179), "مِئَة و تِسْعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(180), "مِئَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(181), "مِئَة و وَاحِد و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(182), "مِئَة و اِثْنَان و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(183), "مِئَة و ثَلَاثَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(184), "مِئَة و أَرْبَعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(185), "مِئَة و خَمْسَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(186), "مِئَة و سِتَّة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(187), "مِئَة و سَبْعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(188), "مِئَة و ثَمَانِيَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(189), "مِئَة و تِسْعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(190), "مِئَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(191), "مِئَة و وَاحِد و تِسْعُونَ")
        XCTAssertEqual(arabic.read(192), "مِئَة و اِثْنَان و تِسْعُونَ")
        XCTAssertEqual(arabic.read(193), "مِئَة و ثَلَاثَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(194), "مِئَة و أَرْبَعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(195), "مِئَة و خَمْسَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(196), "مِئَة و سِتَّة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(197), "مِئَة و سَبْعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(198), "مِئَة و ثَمَانِيَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(199), "مِئَة و تِسْعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(200), "مِا۟ئَتَان")
        XCTAssertEqual(arabic.read(201), "مِا۟ئَتَان و وَاحِد")
        XCTAssertEqual(arabic.read(202), "مِا۟ئَتَان و اِثْنَان")
        XCTAssertEqual(arabic.read(203), "مِا۟ئَتَان و ثَلَاثَة")
        XCTAssertEqual(arabic.read(204), "مِا۟ئَتَان و أَرْبَعَة")
        XCTAssertEqual(arabic.read(205), "مِا۟ئَتَان و خَمْسَة")
        XCTAssertEqual(arabic.read(206), "مِا۟ئَتَان و سِتَّة")
        XCTAssertEqual(arabic.read(207), "مِا۟ئَتَان و سَبْعَة")
        XCTAssertEqual(arabic.read(208), "مِا۟ئَتَان و ثَمَانِيَة")
        XCTAssertEqual(arabic.read(209), "مِا۟ئَتَان و تِسْعَة")
        XCTAssertEqual(arabic.read(210), "مِا۟ئَتَان و عَشَرَة")
        XCTAssertEqual(arabic.read(211), "مِا۟ئَتَان و أَحَدَ عَشَرَ")
        XCTAssertEqual(arabic.read(212), "مِا۟ئَتَان و اِثْنَا عَشَرَ")
        XCTAssertEqual(arabic.read(213), "مِا۟ئَتَان و ثَلَاثَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(214), "مِا۟ئَتَان و أَرْبَعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(215), "مِا۟ئَتَان و خَمْسَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(216), "مِا۟ئَتَان و سِتَّةَ عَشَرَ")
        XCTAssertEqual(arabic.read(217), "مِا۟ئَتَان و سَبْعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(217), "مِئتين و سَبعةَ عَشَرَ")
        XCTAssertEqual(arabic.read(218), "مِا۟ئَتَان و ثَمَانِيَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(219), "مِا۟ئَتَان و تِسْعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(220), "مِا۟ئَتَان و عِشْرُونَ")
        XCTAssertEqual(arabic.read(221), "مِا۟ئَتَان و وَاحِد و عِشْرُونَ")
        XCTAssertEqual(arabic.read(222), "مِا۟ئَتَان و اِثْنَان و عِشْرُونَ")
        XCTAssertEqual(arabic.read(223), "مِا۟ئَتَان و ثَلَاثَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(224), "مِا۟ئَتَان و أَرْبَعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(225), "مِا۟ئَتَان و خَمْسَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(226), "مِا۟ئَتَان و سِتَّة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(227), "مِا۟ئَتَان و سَبْعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(228), "مِا۟ئَتَان و ثَمَانِيَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(229), "مِا۟ئَتَان و تِسْعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(230), "مِا۟ئَتَان و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(231), "مِا۟ئَتَان و وَاحِد و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(232), "مِا۟ئَتَان و اِثْنَان و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(233), "مِا۟ئَتَان و ثَلَاثَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(234), "مِا۟ئَتَان و أَرْبَعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(235), "مِا۟ئَتَان و خَمْسَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(236), "مِا۟ئَتَان و سِتَّة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(237), "مِا۟ئَتَان و سَبْعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(238), "مِا۟ئَتَان و ثَمَانِيَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(239), "مِا۟ئَتَان و تِسْعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(240), "مِا۟ئَتَان و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(241), "مِا۟ئَتَان و وَاحِد و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(242), "مِا۟ئَتَان و اِثْنَان و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(243), "مِا۟ئَتَان و ثَلَاثَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(244), "مِا۟ئَتَان و أَرْبَعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(245), "مِا۟ئَتَان و خَمْسَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(246), "مِا۟ئَتَان و سِتَّة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(247), "مِا۟ئَتَان و سَبْعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(248), "مِا۟ئَتَان و ثَمَانِيَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(249), "مِا۟ئَتَان و تِسْعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(250), "مِا۟ئَتَان و خَمْسُونَ")
        XCTAssertEqual(arabic.read(251), "مِا۟ئَتَان و وَاحِد و خَمْسُونَ")
        XCTAssertEqual(arabic.read(252), "مِا۟ئَتَان و اِثْنَان و خَمْسُونَ")
        XCTAssertEqual(arabic.read(253), "مِا۟ئَتَان و ثَلَاثَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(254), "مِا۟ئَتَان و أَرْبَعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(255), "مِا۟ئَتَان و خَمْسَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(256), "مِا۟ئَتَان و سِتَّة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(257), "مِا۟ئَتَان و سَبْعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(258), "مِا۟ئَتَان و ثَمَانِيَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(259), "مِا۟ئَتَان و تِسْعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(260), "مِا۟ئَتَان و سِتُّونَ")
        XCTAssertEqual(arabic.read(261), "مِا۟ئَتَان و وَاحِد و سِتُّونَ")
        XCTAssertEqual(arabic.read(262), "مِا۟ئَتَان و اِثْنَان و سِتُّونَ")
        XCTAssertEqual(arabic.read(263), "مِا۟ئَتَان و ثَلَاثَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(264), "مِا۟ئَتَان و أَرْبَعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(265), "مِا۟ئَتَان و خَمْسَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(266), "مِا۟ئَتَان و سِتَّة و سِتُّونَ")
        XCTAssertEqual(arabic.read(267), "مِا۟ئَتَان و سَبْعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(268), "مِا۟ئَتَان و ثَمَانِيَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(269), "مِا۟ئَتَان و تِسْعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(270), "مِا۟ئَتَان و سَبْعُونَ")
        XCTAssertEqual(arabic.read(271), "مِا۟ئَتَان و وَاحِد و سَبْعُونَ")
        XCTAssertEqual(arabic.read(272), "مِا۟ئَتَان و اِثْنَان و سَبْعُونَ")
        XCTAssertEqual(arabic.read(273), "مِا۟ئَتَان و ثَلَاثَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(274), "مِا۟ئَتَان و أَرْبَعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(275), "مِا۟ئَتَان و خَمْسَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(276), "مِا۟ئَتَان و سِتَّة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(277), "مِا۟ئَتَان و سَبْعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(278), "مِا۟ئَتَان و ثَمَانِيَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(279), "مِا۟ئَتَان و تِسْعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(280), "مِا۟ئَتَان و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(281), "مِا۟ئَتَان و وَاحِد و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(282), "مِا۟ئَتَان و اِثْنَان و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(283), "مِا۟ئَتَان و ثَلَاثَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(284), "مِا۟ئَتَان و أَرْبَعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(285), "مِا۟ئَتَان و خَمْسَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(286), "مِا۟ئَتَان و سِتَّة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(287), "مِا۟ئَتَان و سَبْعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(288), "مِا۟ئَتَان و ثَمَانِيَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(289), "مِا۟ئَتَان و تِسْعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(290), "مِا۟ئَتَان و تِسْعُونَ")
        XCTAssertEqual(arabic.read(291), "مِا۟ئَتَان و وَاحِد و تِسْعُونَ")
        XCTAssertEqual(arabic.read(292), "مِا۟ئَتَان و اِثْنَان و تِسْعُونَ")
        XCTAssertEqual(arabic.read(293), "مِا۟ئَتَان و ثَلَاثَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(294), "مِا۟ئَتَان و أَرْبَعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(295), "مِا۟ئَتَان و خَمْسَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(296), "مِا۟ئَتَان و سِتَّة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(297), "مِا۟ئَتَان و سَبْعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(298), "مِا۟ئَتَان و ثَمَانِيَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(299), "مِا۟ئَتَان و تِسْعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(300), "ثَلَاثُمِئَة")
        XCTAssertEqual(arabic.read(301), "ثَلَاثُمِئَة و وَاحِد")
        XCTAssertEqual(arabic.read(302), "ثَلَاثُمِئَة و اِثْنَان")
        XCTAssertEqual(arabic.read(303), "ثَلَاثُمِئَة و ثَلَاثَة")
        XCTAssertEqual(arabic.read(304), "ثَلَاثُمِئَة و أَرْبَعَة")
        XCTAssertEqual(arabic.read(305), "ثَلَاثُمِئَة و خَمْسَة")
        XCTAssertEqual(arabic.read(306), "ثَلَاثُمِئَة و سِتَّة")
        XCTAssertEqual(arabic.read(307), "ثَلَاثُمِئَة و سَبْعَة")
        XCTAssertEqual(arabic.read(308), "ثَلَاثُمِئَة و ثَمَانِيَة")
        XCTAssertEqual(arabic.read(309), "ثَلَاثُمِئَة و تِسْعَة")
        XCTAssertEqual(arabic.read(310), "ثَلَاثُمِئَة و عَشَرَة")
        XCTAssertEqual(arabic.read(311), "ثَلَاثُمِئَة و أَحَدَ عَشَرَ")
        XCTAssertEqual(arabic.read(312), "ثَلَاثُمِئَة و اِثْنَا عَشَرَ")
        XCTAssertEqual(arabic.read(313), "ثَلَاثُمِئَة و ثَلَاثَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(314), "ثَلَاثُمِئَة و أَرْبَعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(315), "ثَلَاثُمِئَة و خَمْسَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(316), "ثَلَاثُمِئَة و سِتَّةَ عَشَرَ")
        XCTAssertEqual(arabic.read(317), "ثَلَاثُمِئَة و سَبْعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(318), "ثَلَاثُمِئَة و ثَمَانِيَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(319), "ثَلَاثُمِئَة و تِسْعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(320), "ثَلَاثُمِئَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(321), "ثَلَاثُمِئَة و وَاحِد و عِشْرُونَ")
        XCTAssertEqual(arabic.read(322), "ثَلَاثُمِئَة و اِثْنَان و عِشْرُونَ")
        XCTAssertEqual(arabic.read(323), "ثَلَاثُمِئَة و ثَلَاثَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(324), "ثَلَاثُمِئَة و أَرْبَعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(325), "ثَلَاثُمِئَة و خَمْسَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(326), "ثَلَاثُمِئَة و سِتَّة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(327), "ثَلَاثُمِئَة و سَبْعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(328), "ثَلَاثُمِئَة و ثَمَانِيَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(329), "ثَلَاثُمِئَة و تِسْعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(330), "ثَلَاثُمِئَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(331), "ثَلَاثُمِئَة و وَاحِد و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(332), "ثَلَاثُمِئَة و اِثْنَان و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(333), "ثَلَاثُمِئَة و ثَلَاثَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(334), "ثَلَاثُمِئَة و أَرْبَعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(335), "ثَلَاثُمِئَة و خَمْسَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(336), "ثَلَاثُمِئَة و سِتَّة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(337), "ثَلَاثُمِئَة و سَبْعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(338), "ثَلَاثُمِئَة و ثَمَانِيَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(339), "ثَلَاثُمِئَة و تِسْعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(340), "ثَلَاثُمِئَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(341), "ثَلَاثُمِئَة و وَاحِد و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(342), "ثَلَاثُمِئَة و اِثْنَان و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(343), "ثَلَاثُمِئَة و ثَلَاثَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(344), "ثَلَاثُمِئَة و أَرْبَعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(345), "ثَلَاثُمِئَة و خَمْسَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(346), "ثَلَاثُمِئَة و سِتَّة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(347), "ثَلَاثُمِئَة و سَبْعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(348), "ثَلَاثُمِئَة و ثَمَانِيَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(349), "ثَلَاثُمِئَة و تِسْعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(350), "ثَلَاثُمِئَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(351), "ثَلَاثُمِئَة و وَاحِد و خَمْسُونَ")
        XCTAssertEqual(arabic.read(352), "ثَلَاثُمِئَة و اِثْنَان و خَمْسُونَ")
        XCTAssertEqual(arabic.read(353), "ثَلَاثُمِئَة و ثَلَاثَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(354), "ثَلَاثُمِئَة و أَرْبَعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(355), "ثَلَاثُمِئَة و خَمْسَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(356), "ثَلَاثُمِئَة و سِتَّة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(357), "ثَلَاثُمِئَة و سَبْعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(358), "ثَلَاثُمِئَة و ثَمَانِيَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(359), "ثَلَاثُمِئَة و تِسْعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(360), "ثَلَاثُمِئَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(361), "ثَلَاثُمِئَة و وَاحِد و سِتُّونَ")
        XCTAssertEqual(arabic.read(362), "ثَلَاثُمِئَة و اِثْنَان و سِتُّونَ")
        XCTAssertEqual(arabic.read(363), "ثَلَاثُمِئَة و ثَلَاثَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(364), "ثَلَاثُمِئَة و أَرْبَعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(365), "ثَلَاثُمِئَة و خَمْسَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(366), "ثَلَاثُمِئَة و سِتَّة و سِتُّونَ")
        XCTAssertEqual(arabic.read(367), "ثَلَاثُمِئَة و سَبْعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(368), "ثَلَاثُمِئَة و ثَمَانِيَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(369), "ثَلَاثُمِئَة و تِسْعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(370), "ثَلَاثُمِئَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(371), "ثَلَاثُمِئَة و وَاحِد و سَبْعُونَ")
        XCTAssertEqual(arabic.read(372), "ثَلَاثُمِئَة و اِثْنَان و سَبْعُونَ")
        XCTAssertEqual(arabic.read(373), "ثَلَاثُمِئَة و ثَلَاثَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(374), "ثَلَاثُمِئَة و أَرْبَعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(375), "ثَلَاثُمِئَة و خَمْسَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(376), "ثَلَاثُمِئَة و سِتَّة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(377), "ثَلَاثُمِئَة و سَبْعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(378), "ثَلَاثُمِئَة و ثَمَانِيَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(379), "ثَلَاثُمِئَة و تِسْعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(380), "ثَلَاثُمِئَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(381), "ثَلَاثُمِئَة و وَاحِد و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(382), "ثَلَاثُمِئَة و اِثْنَان و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(383), "ثَلَاثُمِئَة و ثَلَاثَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(384), "ثَلَاثُمِئَة و أَرْبَعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(385), "ثَلَاثُمِئَة و خَمْسَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(386), "ثَلَاثُمِئَة و سِتَّة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(387), "ثَلَاثُمِئَة و سَبْعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(388), "ثَلَاثُمِئَة و ثَمَانِيَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(389), "ثَلَاثُمِئَة و تِسْعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(390), "ثَلَاثُمِئَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(391), "ثَلَاثُمِئَة و وَاحِد و تِسْعُونَ")
        XCTAssertEqual(arabic.read(392), "ثَلَاثُمِئَة و اِثْنَان و تِسْعُونَ")
        XCTAssertEqual(arabic.read(393), "ثَلَاثُمِئَة و ثَلَاثَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(394), "ثَلَاثُمِئَة و أَرْبَعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(395), "ثَلَاثُمِئَة و خَمْسَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(396), "ثَلَاثُمِئَة و سِتَّة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(397), "ثَلَاثُمِئَة و سَبْعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(398), "ثَلَاثُمِئَة و ثَمَانِيَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(399), "ثَلَاثُمِئَة و تِسْعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(400), "أَرْبَعُمِئَة")
        XCTAssertEqual(arabic.read(401), "أَرْبَعُمِئَة و وَاحِد")
        XCTAssertEqual(arabic.read(402), "أَرْبَعُمِئَة و اِثْنَان")
        XCTAssertEqual(arabic.read(403), "أَرْبَعُمِئَة و ثَلَاثَة")
        XCTAssertEqual(arabic.read(404), "أَرْبَعُمِئَة و أَرْبَعَة")
        XCTAssertEqual(arabic.read(405), "أَرْبَعُمِئَة و خَمْسَة")
        XCTAssertEqual(arabic.read(406), "أَرْبَعُمِئَة و سِتَّة")
        XCTAssertEqual(arabic.read(407), "أَرْبَعُمِئَة و سَبْعَة")
        XCTAssertEqual(arabic.read(408), "أَرْبَعُمِئَة و ثَمَانِيَة")
        XCTAssertEqual(arabic.read(409), "أَرْبَعُمِئَة و تِسْعَة")
        XCTAssertEqual(arabic.read(410), "أَرْبَعُمِئَة و عَشَرَة")
        XCTAssertEqual(arabic.read(411), "أَرْبَعُمِئَة و أَحَدَ عَشَرَ")
        XCTAssertEqual(arabic.read(412), "أَرْبَعُمِئَة و اِثْنَا عَشَرَ")
        XCTAssertEqual(arabic.read(413), "أَرْبَعُمِئَة و ثَلَاثَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(414), "أَرْبَعُمِئَة و أَرْبَعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(415), "أَرْبَعُمِئَة و خَمْسَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(416), "أَرْبَعُمِئَة و سِتَّةَ عَشَرَ")
        XCTAssertEqual(arabic.read(417), "أَرْبَعُمِئَة و سَبْعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(418), "أَرْبَعُمِئَة و ثَمَانِيَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(419), "أَرْبَعُمِئَة و تِسْعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(420), "أَرْبَعُمِئَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(421), "أَرْبَعُمِئَة و وَاحِد و عِشْرُونَ")
        XCTAssertEqual(arabic.read(422), "أَرْبَعُمِئَة و اِثْنَان و عِشْرُونَ")
        XCTAssertEqual(arabic.read(423), "أَرْبَعُمِئَة و ثَلَاثَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(424), "أَرْبَعُمِئَة و أَرْبَعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(425), "أَرْبَعُمِئَة و خَمْسَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(426), "أَرْبَعُمِئَة و سِتَّة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(427), "أَرْبَعُمِئَة و سَبْعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(428), "أَرْبَعُمِئَة و ثَمَانِيَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(429), "أَرْبَعُمِئَة و تِسْعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(430), "أَرْبَعُمِئَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(431), "أَرْبَعُمِئَة و وَاحِد و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(432), "أَرْبَعُمِئَة و اِثْنَان و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(433), "أَرْبَعُمِئَة و ثَلَاثَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(434), "أَرْبَعُمِئَة و أَرْبَعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(435), "أَرْبَعُمِئَة و خَمْسَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(436), "أَرْبَعُمِئَة و سِتَّة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(437), "أَرْبَعُمِئَة و سَبْعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(438), "أَرْبَعُمِئَة و ثَمَانِيَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(439), "أَرْبَعُمِئَة و تِسْعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(440), "أَرْبَعُمِئَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(441), "أَرْبَعُمِئَة و وَاحِد و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(442), "أَرْبَعُمِئَة و اِثْنَان و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(443), "أَرْبَعُمِئَة و ثَلَاثَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(444), "أَرْبَعُمِئَة و أَرْبَعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(445), "أَرْبَعُمِئَة و خَمْسَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(446), "أَرْبَعُمِئَة و سِتَّة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(447), "أَرْبَعُمِئَة و سَبْعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(448), "أَرْبَعُمِئَة و ثَمَانِيَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(449), "أَرْبَعُمِئَة و تِسْعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(450), "أَرْبَعُمِئَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(451), "أَرْبَعُمِئَة و وَاحِد و خَمْسُونَ")
        XCTAssertEqual(arabic.read(452), "أَرْبَعُمِئَة و اِثْنَان و خَمْسُونَ")
        XCTAssertEqual(arabic.read(453), "أَرْبَعُمِئَة و ثَلَاثَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(454), "أَرْبَعُمِئَة و أَرْبَعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(455), "أَرْبَعُمِئَة و خَمْسَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(456), "أَرْبَعُمِئَة و سِتَّة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(457), "أَرْبَعُمِئَة و سَبْعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(458), "أَرْبَعُمِئَة و ثَمَانِيَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(459), "أَرْبَعُمِئَة و تِسْعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(460), "أَرْبَعُمِئَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(461), "أَرْبَعُمِئَة و وَاحِد و سِتُّونَ")
        XCTAssertEqual(arabic.read(462), "أَرْبَعُمِئَة و اِثْنَان و سِتُّونَ")
        XCTAssertEqual(arabic.read(463), "أَرْبَعُمِئَة و ثَلَاثَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(464), "أَرْبَعُمِئَة و أَرْبَعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(465), "أَرْبَعُمِئَة و خَمْسَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(466), "أَرْبَعُمِئَة و سِتَّة و سِتُّونَ")
        XCTAssertEqual(arabic.read(467), "أَرْبَعُمِئَة و سَبْعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(468), "أَرْبَعُمِئَة و ثَمَانِيَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(469), "أَرْبَعُمِئَة و تِسْعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(470), "أَرْبَعُمِئَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(471), "أَرْبَعُمِئَة و وَاحِد و سَبْعُونَ")
        XCTAssertEqual(arabic.read(472), "أَرْبَعُمِئَة و اِثْنَان و سَبْعُونَ")
        XCTAssertEqual(arabic.read(473), "أَرْبَعُمِئَة و ثَلَاثَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(474), "أَرْبَعُمِئَة و أَرْبَعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(475), "أَرْبَعُمِئَة و خَمْسَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(476), "أَرْبَعُمِئَة و سِتَّة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(477), "أَرْبَعُمِئَة و سَبْعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(478), "أَرْبَعُمِئَة و ثَمَانِيَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(479), "أَرْبَعُمِئَة و تِسْعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(480), "أَرْبَعُمِئَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(481), "أَرْبَعُمِئَة و وَاحِد و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(482), "أَرْبَعُمِئَة و اِثْنَان و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(483), "أَرْبَعُمِئَة و ثَلَاثَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(484), "أَرْبَعُمِئَة و أَرْبَعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(485), "أَرْبَعُمِئَة و خَمْسَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(486), "أَرْبَعُمِئَة و سِتَّة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(487), "أَرْبَعُمِئَة و سَبْعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(488), "أَرْبَعُمِئَة و ثَمَانِيَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(489), "أَرْبَعُمِئَة و تِسْعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(490), "أَرْبَعُمِئَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(491), "أَرْبَعُمِئَة و وَاحِد و تِسْعُونَ")
        XCTAssertEqual(arabic.read(492), "أَرْبَعُمِئَة و اِثْنَان و تِسْعُونَ")
        XCTAssertEqual(arabic.read(493), "أَرْبَعُمِئَة و ثَلَاثَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(494), "أَرْبَعُمِئَة و أَرْبَعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(495), "أَرْبَعُمِئَة و خَمْسَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(496), "أَرْبَعُمِئَة و سِتَّة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(497), "أَرْبَعُمِئَة و سَبْعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(498), "أَرْبَعُمِئَة و ثَمَانِيَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(499), "أَرْبَعُمِئَة و تِسْعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(500), "خُمْسُمِئَة")
        XCTAssertEqual(arabic.read(501), "خُمْسُمِئَة و وَاحِد")
        XCTAssertEqual(arabic.read(502), "خُمْسُمِئَة و اِثْنَان")
        XCTAssertEqual(arabic.read(503), "خُمْسُمِئَة و ثَلَاثَة")
        XCTAssertEqual(arabic.read(504), "خُمْسُمِئَة و أَرْبَعَة")
        XCTAssertEqual(arabic.read(505), "خُمْسُمِئَة و خَمْسَة")
        XCTAssertEqual(arabic.read(506), "خُمْسُمِئَة و سِتَّة")
        XCTAssertEqual(arabic.read(507), "خُمْسُمِئَة و سَبْعَة")
        XCTAssertEqual(arabic.read(508), "خُمْسُمِئَة و ثَمَانِيَة")
        XCTAssertEqual(arabic.read(509), "خُمْسُمِئَة و تِسْعَة")
        XCTAssertEqual(arabic.read(510), "خُمْسُمِئَة و عَشَرَة")
        XCTAssertEqual(arabic.read(511), "خُمْسُمِئَة و أَحَدَ عَشَرَ")
        XCTAssertEqual(arabic.read(512), "خُمْسُمِئَة و اِثْنَا عَشَرَ")
        XCTAssertEqual(arabic.read(513), "خُمْسُمِئَة و ثَلَاثَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(514), "خُمْسُمِئَة و أَرْبَعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(515), "خُمْسُمِئَة و خَمْسَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(516), "خُمْسُمِئَة و سِتَّةَ عَشَرَ")
        XCTAssertEqual(arabic.read(517), "خُمْسُمِئَة و سَبْعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(518), "خُمْسُمِئَة و ثَمَانِيَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(519), "خُمْسُمِئَة و تِسْعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(520), "خُمْسُمِئَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(521), "خُمْسُمِئَة و وَاحِد و عِشْرُونَ")
        XCTAssertEqual(arabic.read(522), "خُمْسُمِئَة و اِثْنَان و عِشْرُونَ")
        XCTAssertEqual(arabic.read(523), "خُمْسُمِئَة و ثَلَاثَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(524), "خُمْسُمِئَة و أَرْبَعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(525), "خُمْسُمِئَة و خَمْسَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(526), "خُمْسُمِئَة و سِتَّة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(527), "خُمْسُمِئَة و سَبْعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(528), "خُمْسُمِئَة و ثَمَانِيَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(529), "خُمْسُمِئَة و تِسْعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(530), "خُمْسُمِئَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(531), "خُمْسُمِئَة و وَاحِد و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(532), "خُمْسُمِئَة و اِثْنَان و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(533), "خُمْسُمِئَة و ثَلَاثَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(534), "خُمْسُمِئَة و أَرْبَعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(535), "خُمْسُمِئَة و خَمْسَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(536), "خُمْسُمِئَة و سِتَّة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(537), "خُمْسُمِئَة و سَبْعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(538), "خُمْسُمِئَة و ثَمَانِيَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(539), "خُمْسُمِئَة و تِسْعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(540), "خُمْسُمِئَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(541), "خُمْسُمِئَة و وَاحِد و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(542), "خُمْسُمِئَة و اِثْنَان و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(543), "خُمْسُمِئَة و ثَلَاثَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(544), "خُمْسُمِئَة و أَرْبَعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(545), "خُمْسُمِئَة و خَمْسَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(546), "خُمْسُمِئَة و سِتَّة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(547), "خُمْسُمِئَة و سَبْعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(548), "خُمْسُمِئَة و ثَمَانِيَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(549), "خُمْسُمِئَة و تِسْعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(550), "خُمْسُمِئَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(551), "خُمْسُمِئَة و وَاحِد و خَمْسُونَ")
        XCTAssertEqual(arabic.read(552), "خُمْسُمِئَة و اِثْنَان و خَمْسُونَ")
        XCTAssertEqual(arabic.read(553), "خُمْسُمِئَة و ثَلَاثَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(554), "خُمْسُمِئَة و أَرْبَعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(555), "خُمْسُمِئَة و خَمْسَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(556), "خُمْسُمِئَة و سِتَّة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(557), "خُمْسُمِئَة و سَبْعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(558), "خُمْسُمِئَة و ثَمَانِيَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(559), "خُمْسُمِئَة و تِسْعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(560), "خُمْسُمِئَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(561), "خُمْسُمِئَة و وَاحِد و سِتُّونَ")
        XCTAssertEqual(arabic.read(562), "خُمْسُمِئَة و اِثْنَان و سِتُّونَ")
        XCTAssertEqual(arabic.read(563), "خُمْسُمِئَة و ثَلَاثَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(564), "خُمْسُمِئَة و أَرْبَعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(565), "خُمْسُمِئَة و خَمْسَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(566), "خُمْسُمِئَة و سِتَّة و سِتُّونَ")
        XCTAssertEqual(arabic.read(567), "خُمْسُمِئَة و سَبْعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(568), "خُمْسُمِئَة و ثَمَانِيَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(569), "خُمْسُمِئَة و تِسْعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(570), "خُمْسُمِئَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(571), "خُمْسُمِئَة و وَاحِد و سَبْعُونَ")
        XCTAssertEqual(arabic.read(572), "خُمْسُمِئَة و اِثْنَان و سَبْعُونَ")
        XCTAssertEqual(arabic.read(573), "خُمْسُمِئَة و ثَلَاثَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(574), "خُمْسُمِئَة و أَرْبَعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(575), "خُمْسُمِئَة و خَمْسَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(576), "خُمْسُمِئَة و سِتَّة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(577), "خُمْسُمِئَة و سَبْعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(578), "خُمْسُمِئَة و ثَمَانِيَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(579), "خُمْسُمِئَة و تِسْعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(580), "خُمْسُمِئَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(581), "خُمْسُمِئَة و وَاحِد و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(582), "خُمْسُمِئَة و اِثْنَان و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(583), "خُمْسُمِئَة و ثَلَاثَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(584), "خُمْسُمِئَة و أَرْبَعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(585), "خُمْسُمِئَة و خَمْسَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(586), "خُمْسُمِئَة و سِتَّة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(587), "خُمْسُمِئَة و سَبْعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(588), "خُمْسُمِئَة و ثَمَانِيَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(589), "خُمْسُمِئَة و تِسْعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(590), "خُمْسُمِئَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(591), "خُمْسُمِئَة و وَاحِد و تِسْعُونَ")
        XCTAssertEqual(arabic.read(592), "خُمْسُمِئَة و اِثْنَان و تِسْعُونَ")
        XCTAssertEqual(arabic.read(593), "خُمْسُمِئَة و ثَلَاثَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(594), "خُمْسُمِئَة و أَرْبَعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(595), "خُمْسُمِئَة و خَمْسَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(596), "خُمْسُمِئَة و سِتَّة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(597), "خُمْسُمِئَة و سَبْعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(598), "خُمْسُمِئَة و ثَمَانِيَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(599), "خُمْسُمِئَة و تِسْعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(600), "سِتُّمِئَة")
        XCTAssertEqual(arabic.read(601), "سِتُّمِئَة و وَاحِد")
        XCTAssertEqual(arabic.read(602), "سِتُّمِئَة و اِثْنَان")
        XCTAssertEqual(arabic.read(603), "سِتُّمِئَة و ثَلَاثَة")
        XCTAssertEqual(arabic.read(604), "سِتُّمِئَة و أَرْبَعَة")
        XCTAssertEqual(arabic.read(605), "سِتُّمِئَة و خَمْسَة")
        XCTAssertEqual(arabic.read(606), "سِتُّمِئَة و سِتَّة")
        XCTAssertEqual(arabic.read(607), "سِتُّمِئَة و سَبْعَة")
        XCTAssertEqual(arabic.read(608), "سِتُّمِئَة و ثَمَانِيَة")
        XCTAssertEqual(arabic.read(609), "سِتُّمِئَة و تِسْعَة")
        XCTAssertEqual(arabic.read(610), "سِتُّمِئَة و عَشَرَة")
        XCTAssertEqual(arabic.read(611), "سِتُّمِئَة و أَحَدَ عَشَرَ")
        XCTAssertEqual(arabic.read(612), "سِتُّمِئَة و اِثْنَا عَشَرَ")
        XCTAssertEqual(arabic.read(613), "سِتُّمِئَة و ثَلَاثَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(614), "سِتُّمِئَة و أَرْبَعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(615), "سِتُّمِئَة و خَمْسَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(616), "سِتُّمِئَة و سِتَّةَ عَشَرَ")
        XCTAssertEqual(arabic.read(617), "سِتُّمِئَة و سَبْعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(618), "سِتُّمِئَة و ثَمَانِيَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(619), "سِتُّمِئَة و تِسْعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(620), "سِتُّمِئَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(621), "سِتُّمِئَة و وَاحِد و عِشْرُونَ")
        XCTAssertEqual(arabic.read(622), "سِتُّمِئَة و اِثْنَان و عِشْرُونَ")
        XCTAssertEqual(arabic.read(623), "سِتُّمِئَة و ثَلَاثَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(624), "سِتُّمِئَة و أَرْبَعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(625), "سِتُّمِئَة و خَمْسَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(626), "سِتُّمِئَة و سِتَّة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(627), "سِتُّمِئَة و سَبْعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(628), "سِتُّمِئَة و ثَمَانِيَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(629), "سِتُّمِئَة و تِسْعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(630), "سِتُّمِئَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(631), "سِتُّمِئَة و وَاحِد و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(632), "سِتُّمِئَة و اِثْنَان و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(633), "سِتُّمِئَة و ثَلَاثَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(634), "سِتُّمِئَة و أَرْبَعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(635), "سِتُّمِئَة و خَمْسَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(636), "سِتُّمِئَة و سِتَّة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(637), "سِتُّمِئَة و سَبْعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(638), "سِتُّمِئَة و ثَمَانِيَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(639), "سِتُّمِئَة و تِسْعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(640), "سِتُّمِئَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(641), "سِتُّمِئَة و وَاحِد و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(642), "سِتُّمِئَة و اِثْنَان و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(643), "سِتُّمِئَة و ثَلَاثَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(644), "سِتُّمِئَة و أَرْبَعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(645), "سِتُّمِئَة و خَمْسَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(646), "سِتُّمِئَة و سِتَّة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(647), "سِتُّمِئَة و سَبْعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(648), "سِتُّمِئَة و ثَمَانِيَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(649), "سِتُّمِئَة و تِسْعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(650), "سِتُّمِئَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(651), "سِتُّمِئَة و وَاحِد و خَمْسُونَ")
        XCTAssertEqual(arabic.read(652), "سِتُّمِئَة و اِثْنَان و خَمْسُونَ")
        XCTAssertEqual(arabic.read(653), "سِتُّمِئَة و ثَلَاثَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(654), "سِتُّمِئَة و أَرْبَعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(655), "سِتُّمِئَة و خَمْسَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(656), "سِتُّمِئَة و سِتَّة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(657), "سِتُّمِئَة و سَبْعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(658), "سِتُّمِئَة و ثَمَانِيَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(659), "سِتُّمِئَة و تِسْعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(660), "سِتُّمِئَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(661), "سِتُّمِئَة و وَاحِد و سِتُّونَ")
        XCTAssertEqual(arabic.read(662), "سِتُّمِئَة و اِثْنَان و سِتُّونَ")
        XCTAssertEqual(arabic.read(663), "سِتُّمِئَة و ثَلَاثَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(664), "سِتُّمِئَة و أَرْبَعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(665), "سِتُّمِئَة و خَمْسَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(666), "سِتُّمِئَة و سِتَّة و سِتُّونَ")
        XCTAssertEqual(arabic.read(667), "سِتُّمِئَة و سَبْعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(668), "سِتُّمِئَة و ثَمَانِيَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(669), "سِتُّمِئَة و تِسْعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(670), "سِتُّمِئَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(671), "سِتُّمِئَة و وَاحِد و سَبْعُونَ")
        XCTAssertEqual(arabic.read(672), "سِتُّمِئَة و اِثْنَان و سَبْعُونَ")
        XCTAssertEqual(arabic.read(673), "سِتُّمِئَة و ثَلَاثَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(674), "سِتُّمِئَة و أَرْبَعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(675), "سِتُّمِئَة و خَمْسَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(676), "سِتُّمِئَة و سِتَّة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(677), "سِتُّمِئَة و سَبْعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(678), "سِتُّمِئَة و ثَمَانِيَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(679), "سِتُّمِئَة و تِسْعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(680), "سِتُّمِئَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(681), "سِتُّمِئَة و وَاحِد و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(682), "سِتُّمِئَة و اِثْنَان و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(683), "سِتُّمِئَة و ثَلَاثَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(684), "سِتُّمِئَة و أَرْبَعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(685), "سِتُّمِئَة و خَمْسَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(686), "سِتُّمِئَة و سِتَّة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(687), "سِتُّمِئَة و سَبْعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(688), "سِتُّمِئَة و ثَمَانِيَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(689), "سِتُّمِئَة و تِسْعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(690), "سِتُّمِئَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(691), "سِتُّمِئَة و وَاحِد و تِسْعُونَ")
        XCTAssertEqual(arabic.read(692), "سِتُّمِئَة و اِثْنَان و تِسْعُونَ")
        XCTAssertEqual(arabic.read(693), "سِتُّمِئَة و ثَلَاثَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(694), "سِتُّمِئَة و أَرْبَعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(695), "سِتُّمِئَة و خَمْسَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(696), "سِتُّمِئَة و سِتَّة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(697), "سِتُّمِئَة و سَبْعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(698), "سِتُّمِئَة و ثَمَانِيَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(699), "سِتُّمِئَة و تِسْعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(700), "سَبْعُمِئَة")
        XCTAssertEqual(arabic.read(701), "سَبْعُمِئَة و وَاحِد")
        XCTAssertEqual(arabic.read(702), "سَبْعُمِئَة و اِثْنَان")
        XCTAssertEqual(arabic.read(703), "سَبْعُمِئَة و ثَلَاثَة")
        XCTAssertEqual(arabic.read(704), "سَبْعُمِئَة و أَرْبَعَة")
        XCTAssertEqual(arabic.read(705), "سَبْعُمِئَة و خَمْسَة")
        XCTAssertEqual(arabic.read(706), "سَبْعُمِئَة و سِتَّة")
        XCTAssertEqual(arabic.read(707), "سَبْعُمِئَة و سَبْعَة")
        XCTAssertEqual(arabic.read(708), "سَبْعُمِئَة و ثَمَانِيَة")
        XCTAssertEqual(arabic.read(709), "سَبْعُمِئَة و تِسْعَة")
        XCTAssertEqual(arabic.read(710), "سَبْعُمِئَة و عَشَرَة")
        XCTAssertEqual(arabic.read(711), "سَبْعُمِئَة و أَحَدَ عَشَرَ")
        XCTAssertEqual(arabic.read(712), "سَبْعُمِئَة و اِثْنَا عَشَرَ")
        XCTAssertEqual(arabic.read(713), "سَبْعُمِئَة و ثَلَاثَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(714), "سَبْعُمِئَة و أَرْبَعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(715), "سَبْعُمِئَة و خَمْسَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(716), "سَبْعُمِئَة و سِتَّةَ عَشَرَ")
        XCTAssertEqual(arabic.read(717), "سَبْعُمِئَة و سَبْعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(718), "سَبْعُمِئَة و ثَمَانِيَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(719), "سَبْعُمِئَة و تِسْعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(720), "سَبْعُمِئَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(721), "سَبْعُمِئَة و وَاحِد و عِشْرُونَ")
        XCTAssertEqual(arabic.read(722), "سَبْعُمِئَة و اِثْنَان و عِشْرُونَ")
        XCTAssertEqual(arabic.read(723), "سَبْعُمِئَة و ثَلَاثَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(724), "سَبْعُمِئَة و أَرْبَعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(725), "سَبْعُمِئَة و خَمْسَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(726), "سَبْعُمِئَة و سِتَّة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(727), "سَبْعُمِئَة و سَبْعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(728), "سَبْعُمِئَة و ثَمَانِيَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(729), "سَبْعُمِئَة و تِسْعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(730), "سَبْعُمِئَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(731), "سَبْعُمِئَة و وَاحِد و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(732), "سَبْعُمِئَة و اِثْنَان و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(733), "سَبْعُمِئَة و ثَلَاثَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(734), "سَبْعُمِئَة و أَرْبَعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(735), "سَبْعُمِئَة و خَمْسَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(736), "سَبْعُمِئَة و سِتَّة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(737), "سَبْعُمِئَة و سَبْعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(738), "سَبْعُمِئَة و ثَمَانِيَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(739), "سَبْعُمِئَة و تِسْعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(740), "سَبْعُمِئَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(741), "سَبْعُمِئَة و وَاحِد و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(742), "سَبْعُمِئَة و اِثْنَان و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(743), "سَبْعُمِئَة و ثَلَاثَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(744), "سَبْعُمِئَة و أَرْبَعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(745), "سَبْعُمِئَة و خَمْسَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(746), "سَبْعُمِئَة و سِتَّة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(747), "سَبْعُمِئَة و سَبْعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(748), "سَبْعُمِئَة و ثَمَانِيَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(749), "سَبْعُمِئَة و تِسْعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(750), "سَبْعُمِئَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(751), "سَبْعُمِئَة و وَاحِد و خَمْسُونَ")
        XCTAssertEqual(arabic.read(752), "سَبْعُمِئَة و اِثْنَان و خَمْسُونَ")
        XCTAssertEqual(arabic.read(753), "سَبْعُمِئَة و ثَلَاثَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(754), "سَبْعُمِئَة و أَرْبَعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(755), "سَبْعُمِئَة و خَمْسَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(756), "سَبْعُمِئَة و سِتَّة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(757), "سَبْعُمِئَة و سَبْعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(758), "سَبْعُمِئَة و ثَمَانِيَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(759), "سَبْعُمِئَة و تِسْعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(760), "سَبْعُمِئَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(761), "سَبْعُمِئَة و وَاحِد و سِتُّونَ")
        XCTAssertEqual(arabic.read(762), "سَبْعُمِئَة و اِثْنَان و سِتُّونَ")
        XCTAssertEqual(arabic.read(763), "سَبْعُمِئَة و ثَلَاثَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(764), "سَبْعُمِئَة و أَرْبَعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(765), "سَبْعُمِئَة و خَمْسَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(766), "سَبْعُمِئَة و سِتَّة و سِتُّونَ")
        XCTAssertEqual(arabic.read(767), "سَبْعُمِئَة و سَبْعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(768), "سَبْعُمِئَة و ثَمَانِيَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(769), "سَبْعُمِئَة و تِسْعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(770), "سَبْعُمِئَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(771), "سَبْعُمِئَة و وَاحِد و سَبْعُونَ")
        XCTAssertEqual(arabic.read(772), "سَبْعُمِئَة و اِثْنَان و سَبْعُونَ")
        XCTAssertEqual(arabic.read(773), "سَبْعُمِئَة و ثَلَاثَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(774), "سَبْعُمِئَة و أَرْبَعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(775), "سَبْعُمِئَة و خَمْسَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(776), "سَبْعُمِئَة و سِتَّة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(777), "سَبْعُمِئَة و سَبْعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(778), "سَبْعُمِئَة و ثَمَانِيَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(779), "سَبْعُمِئَة و تِسْعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(780), "سَبْعُمِئَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(781), "سَبْعُمِئَة و وَاحِد و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(782), "سَبْعُمِئَة و اِثْنَان و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(783), "سَبْعُمِئَة و ثَلَاثَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(784), "سَبْعُمِئَة و أَرْبَعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(785), "سَبْعُمِئَة و خَمْسَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(786), "سَبْعُمِئَة و سِتَّة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(787), "سَبْعُمِئَة و سَبْعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(788), "سَبْعُمِئَة و ثَمَانِيَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(789), "سَبْعُمِئَة و تِسْعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(790), "سَبْعُمِئَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(791), "سَبْعُمِئَة و وَاحِد و تِسْعُونَ")
        XCTAssertEqual(arabic.read(792), "سَبْعُمِئَة و اِثْنَان و تِسْعُونَ")
        XCTAssertEqual(arabic.read(793), "سَبْعُمِئَة و ثَلَاثَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(794), "سَبْعُمِئَة و أَرْبَعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(795), "سَبْعُمِئَة و خَمْسَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(796), "سَبْعُمِئَة و سِتَّة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(797), "سَبْعُمِئَة و سَبْعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(798), "سَبْعُمِئَة و ثَمَانِيَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(799), "سَبْعُمِئَة و تِسْعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(800), "ثَمَانِيُمِئَة")
        XCTAssertEqual(arabic.read(801), "ثَمَانِيُمِئَة و وَاحِد")
        XCTAssertEqual(arabic.read(802), "ثَمَانِيُمِئَة و اِثْنَان")
        XCTAssertEqual(arabic.read(803), "ثَمَانِيُمِئَة و ثَلَاثَة")
        XCTAssertEqual(arabic.read(804), "ثَمَانِيُمِئَة و أَرْبَعَة")
        XCTAssertEqual(arabic.read(805), "ثَمَانِيُمِئَة و خَمْسَة")
        XCTAssertEqual(arabic.read(806), "ثَمَانِيُمِئَة و سِتَّة")
        XCTAssertEqual(arabic.read(807), "ثَمَانِيُمِئَة و سَبْعَة")
        XCTAssertEqual(arabic.read(808), "ثَمَانِيُمِئَة و ثَمَانِيَة")
        XCTAssertEqual(arabic.read(809), "ثَمَانِيُمِئَة و تِسْعَة")
        XCTAssertEqual(arabic.read(810), "ثَمَانِيُمِئَة و عَشَرَة")
        XCTAssertEqual(arabic.read(811), "ثَمَانِيُمِئَة و أَحَدَ عَشَرَ")
        XCTAssertEqual(arabic.read(812), "ثَمَانِيُمِئَة و اِثْنَا عَشَرَ")
        XCTAssertEqual(arabic.read(813), "ثَمَانِيُمِئَة و ثَلَاثَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(814), "ثَمَانِيُمِئَة و أَرْبَعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(815), "ثَمَانِيُمِئَة و خَمْسَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(816), "ثَمَانِيُمِئَة و سِتَّةَ عَشَرَ")
        XCTAssertEqual(arabic.read(817), "ثَمَانِيُمِئَة و سَبْعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(818), "ثَمَانِيُمِئَة و ثَمَانِيَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(819), "ثَمَانِيُمِئَة و تِسْعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(820), "ثَمَانِيُمِئَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(821), "ثَمَانِيُمِئَة و وَاحِد و عِشْرُونَ")
        XCTAssertEqual(arabic.read(822), "ثَمَانِيُمِئَة و اِثْنَان و عِشْرُونَ")
        XCTAssertEqual(arabic.read(823), "ثَمَانِيُمِئَة و ثَلَاثَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(824), "ثَمَانِيُمِئَة و أَرْبَعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(825), "ثَمَانِيُمِئَة و خَمْسَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(826), "ثَمَانِيُمِئَة و سِتَّة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(827), "ثَمَانِيُمِئَة و سَبْعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(828), "ثَمَانِيُمِئَة و ثَمَانِيَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(829), "ثَمَانِيُمِئَة و تِسْعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(830), "ثَمَانِيُمِئَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(831), "ثَمَانِيُمِئَة و وَاحِد و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(832), "ثَمَانِيُمِئَة و اِثْنَان و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(833), "ثَمَانِيُمِئَة و ثَلَاثَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(834), "ثَمَانِيُمِئَة و أَرْبَعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(835), "ثَمَانِيُمِئَة و خَمْسَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(836), "ثَمَانِيُمِئَة و سِتَّة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(837), "ثَمَانِيُمِئَة و سَبْعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(838), "ثَمَانِيُمِئَة و ثَمَانِيَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(839), "ثَمَانِيُمِئَة و تِسْعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(840), "ثَمَانِيُمِئَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(841), "ثَمَانِيُمِئَة و وَاحِد و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(842), "ثَمَانِيُمِئَة و اِثْنَان و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(843), "ثَمَانِيُمِئَة و ثَلَاثَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(844), "ثَمَانِيُمِئَة و أَرْبَعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(845), "ثَمَانِيُمِئَة و خَمْسَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(846), "ثَمَانِيُمِئَة و سِتَّة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(847), "ثَمَانِيُمِئَة و سَبْعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(848), "ثَمَانِيُمِئَة و ثَمَانِيَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(849), "ثَمَانِيُمِئَة و تِسْعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(850), "ثَمَانِيُمِئَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(851), "ثَمَانِيُمِئَة و وَاحِد و خَمْسُونَ")
        XCTAssertEqual(arabic.read(852), "ثَمَانِيُمِئَة و اِثْنَان و خَمْسُونَ")
        XCTAssertEqual(arabic.read(853), "ثَمَانِيُمِئَة و ثَلَاثَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(854), "ثَمَانِيُمِئَة و أَرْبَعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(855), "ثَمَانِيُمِئَة و خَمْسَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(856), "ثَمَانِيُمِئَة و سِتَّة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(857), "ثَمَانِيُمِئَة و سَبْعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(858), "ثَمَانِيُمِئَة و ثَمَانِيَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(859), "ثَمَانِيُمِئَة و تِسْعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(860), "ثَمَانِيُمِئَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(861), "ثَمَانِيُمِئَة و وَاحِد و سِتُّونَ")
        XCTAssertEqual(arabic.read(862), "ثَمَانِيُمِئَة و اِثْنَان و سِتُّونَ")
        XCTAssertEqual(arabic.read(863), "ثَمَانِيُمِئَة و ثَلَاثَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(864), "ثَمَانِيُمِئَة و أَرْبَعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(865), "ثَمَانِيُمِئَة و خَمْسَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(866), "ثَمَانِيُمِئَة و سِتَّة و سِتُّونَ")
        XCTAssertEqual(arabic.read(867), "ثَمَانِيُمِئَة و سَبْعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(868), "ثَمَانِيُمِئَة و ثَمَانِيَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(869), "ثَمَانِيُمِئَة و تِسْعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(870), "ثَمَانِيُمِئَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(871), "ثَمَانِيُمِئَة و وَاحِد و سَبْعُونَ")
        XCTAssertEqual(arabic.read(872), "ثَمَانِيُمِئَة و اِثْنَان و سَبْعُونَ")
        XCTAssertEqual(arabic.read(873), "ثَمَانِيُمِئَة و ثَلَاثَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(874), "ثَمَانِيُمِئَة و أَرْبَعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(875), "ثَمَانِيُمِئَة و خَمْسَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(876), "ثَمَانِيُمِئَة و سِتَّة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(877), "ثَمَانِيُمِئَة و سَبْعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(878), "ثَمَانِيُمِئَة و ثَمَانِيَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(879), "ثَمَانِيُمِئَة و تِسْعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(880), "ثَمَانِيُمِئَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(881), "ثَمَانِيُمِئَة و وَاحِد و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(882), "ثَمَانِيُمِئَة و اِثْنَان و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(883), "ثَمَانِيُمِئَة و ثَلَاثَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(884), "ثَمَانِيُمِئَة و أَرْبَعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(885), "ثَمَانِيُمِئَة و خَمْسَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(886), "ثَمَانِيُمِئَة و سِتَّة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(887), "ثَمَانِيُمِئَة و سَبْعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(888), "ثَمَانِيُمِئَة و ثَمَانِيَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(889), "ثَمَانِيُمِئَة و تِسْعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(890), "ثَمَانِيُمِئَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(891), "ثَمَانِيُمِئَة و وَاحِد و تِسْعُونَ")
        XCTAssertEqual(arabic.read(892), "ثَمَانِيُمِئَة و اِثْنَان و تِسْعُونَ")
        XCTAssertEqual(arabic.read(893), "ثَمَانِيُمِئَة و ثَلَاثَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(894), "ثَمَانِيُمِئَة و أَرْبَعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(895), "ثَمَانِيُمِئَة و خَمْسَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(896), "ثَمَانِيُمِئَة و سِتَّة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(897), "ثَمَانِيُمِئَة و سَبْعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(898), "ثَمَانِيُمِئَة و ثَمَانِيَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(899), "ثَمَانِيُمِئَة و تِسْعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(900), "تِسْعُمِئَة")
        XCTAssertEqual(arabic.read(901), "تِسْعُمِئَة و وَاحِد")
        XCTAssertEqual(arabic.read(902), "تِسْعُمِئَة و اِثْنَان")
        XCTAssertEqual(arabic.read(903), "تِسْعُمِئَة و ثَلَاثَة")
        XCTAssertEqual(arabic.read(904), "تِسْعُمِئَة و أَرْبَعَة")
        XCTAssertEqual(arabic.read(905), "تِسْعُمِئَة و خَمْسَة")
        XCTAssertEqual(arabic.read(906), "تِسْعُمِئَة و سِتَّة")
        XCTAssertEqual(arabic.read(907), "تِسْعُمِئَة و سَبْعَة")
        XCTAssertEqual(arabic.read(908), "تِسْعُمِئَة و ثَمَانِيَة")
        XCTAssertEqual(arabic.read(909), "تِسْعُمِئَة و تِسْعَة")
        XCTAssertEqual(arabic.read(910), "تِسْعُمِئَة و عَشَرَة")
        XCTAssertEqual(arabic.read(911), "تِسْعُمِئَة و أَحَدَ عَشَرَ")
        XCTAssertEqual(arabic.read(912), "تِسْعُمِئَة و اِثْنَا عَشَرَ")
        XCTAssertEqual(arabic.read(913), "تِسْعُمِئَة و ثَلَاثَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(914), "تِسْعُمِئَة و أَرْبَعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(915), "تِسْعُمِئَة و خَمْسَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(916), "تِسْعُمِئَة و سِتَّةَ عَشَرَ")
        XCTAssertEqual(arabic.read(917), "تِسْعُمِئَة و سَبْعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(918), "تِسْعُمِئَة و ثَمَانِيَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(919), "تِسْعُمِئَة و تِسْعَةَ عَشَرَ")
        XCTAssertEqual(arabic.read(920), "تِسْعُمِئَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(921), "تِسْعُمِئَة و وَاحِد و عِشْرُونَ")
        XCTAssertEqual(arabic.read(922), "تِسْعُمِئَة و اِثْنَان و عِشْرُونَ")
        XCTAssertEqual(arabic.read(923), "تِسْعُمِئَة و ثَلَاثَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(924), "تِسْعُمِئَة و أَرْبَعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(925), "تِسْعُمِئَة و خَمْسَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(926), "تِسْعُمِئَة و سِتَّة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(927), "تِسْعُمِئَة و سَبْعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(928), "تِسْعُمِئَة و ثَمَانِيَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(929), "تِسْعُمِئَة و تِسْعَة و عِشْرُونَ")
        XCTAssertEqual(arabic.read(930), "تِسْعُمِئَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(931), "تِسْعُمِئَة و وَاحِد و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(932), "تِسْعُمِئَة و اِثْنَان و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(933), "تِسْعُمِئَة و ثَلَاثَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(934), "تِسْعُمِئَة و أَرْبَعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(935), "تِسْعُمِئَة و خَمْسَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(936), "تِسْعُمِئَة و سِتَّة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(937), "تِسْعُمِئَة و سَبْعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(938), "تِسْعُمِئَة و ثَمَانِيَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(939), "تِسْعُمِئَة و تِسْعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(940), "تِسْعُمِئَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(941), "تِسْعُمِئَة و وَاحِد و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(942), "تِسْعُمِئَة و اِثْنَان و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(943), "تِسْعُمِئَة و ثَلَاثَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(944), "تِسْعُمِئَة و أَرْبَعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(945), "تِسْعُمِئَة و خَمْسَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(946), "تِسْعُمِئَة و سِتَّة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(947), "تِسْعُمِئَة و سَبْعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(948), "تِسْعُمِئَة و ثَمَانِيَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(949), "تِسْعُمِئَة و تِسْعَة و أَرْبَعُونَ")
        XCTAssertEqual(arabic.read(950), "تِسْعُمِئَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(951), "تِسْعُمِئَة و وَاحِد و خَمْسُونَ")
        XCTAssertEqual(arabic.read(952), "تِسْعُمِئَة و اِثْنَان و خَمْسُونَ")
        XCTAssertEqual(arabic.read(953), "تِسْعُمِئَة و ثَلَاثَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(954), "تِسْعُمِئَة و أَرْبَعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(955), "تِسْعُمِئَة و خَمْسَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(956), "تِسْعُمِئَة و سِتَّة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(957), "تِسْعُمِئَة و سَبْعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(958), "تِسْعُمِئَة و ثَمَانِيَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(959), "تِسْعُمِئَة و تِسْعَة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(960), "تِسْعُمِئَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(961), "تِسْعُمِئَة و وَاحِد و سِتُّونَ")
        XCTAssertEqual(arabic.read(962), "تِسْعُمِئَة و اِثْنَان و سِتُّونَ")
        XCTAssertEqual(arabic.read(963), "تِسْعُمِئَة و ثَلَاثَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(964), "تِسْعُمِئَة و أَرْبَعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(965), "تِسْعُمِئَة و خَمْسَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(966), "تِسْعُمِئَة و سِتَّة و سِتُّونَ")
        XCTAssertEqual(arabic.read(967), "تِسْعُمِئَة و سَبْعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(968), "تِسْعُمِئَة و ثَمَانِيَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(969), "تِسْعُمِئَة و تِسْعَة و سِتُّونَ")
        XCTAssertEqual(arabic.read(970), "تِسْعُمِئَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(971), "تِسْعُمِئَة و وَاحِد و سَبْعُونَ")
        XCTAssertEqual(arabic.read(972), "تِسْعُمِئَة و اِثْنَان و سَبْعُونَ")
        XCTAssertEqual(arabic.read(973), "تِسْعُمِئَة و ثَلَاثَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(974), "تِسْعُمِئَة و أَرْبَعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(975), "تِسْعُمِئَة و خَمْسَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(976), "تِسْعُمِئَة و سِتَّة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(977), "تِسْعُمِئَة و سَبْعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(978), "تِسْعُمِئَة و ثَمَانِيَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(979), "تِسْعُمِئَة و تِسْعَة و سَبْعُونَ")
        XCTAssertEqual(arabic.read(980), "تِسْعُمِئَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(981), "تِسْعُمِئَة و وَاحِد و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(982), "تِسْعُمِئَة و اِثْنَان و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(983), "تِسْعُمِئَة و ثَلَاثَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(984), "تِسْعُمِئَة و أَرْبَعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(985), "تِسْعُمِئَة و خَمْسَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(986), "تِسْعُمِئَة و سِتَّة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(987), "تِسْعُمِئَة و سَبْعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(988), "تِسْعُمِئَة و ثَمَانِيَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(989), "تِسْعُمِئَة و تِسْعَة و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(990), "تِسْعُمِئَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(991), "تِسْعُمِئَة و وَاحِد و تِسْعُونَ")
        XCTAssertEqual(arabic.read(992), "تِسْعُمِئَة و اِثْنَان و تِسْعُونَ")
        XCTAssertEqual(arabic.read(993), "تِسْعُمِئَة و ثَلَاثَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(994), "تِسْعُمِئَة و أَرْبَعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(995), "تِسْعُمِئَة و خَمْسَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(996), "تِسْعُمِئَة و سِتَّة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(997), "تِسْعُمِئَة و سَبْعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(998), "تِسْعُمِئَة و ثَمَانِيَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(999), "تِسْعُمِئَة و تِسْعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(1000), "أَلف")
        XCTAssertEqual(arabic.read(1001), "أَلف و وَاحِد")
        XCTAssertEqual(arabic.read(1002), "أَلف و اِثْنَان")
        XCTAssertEqual(arabic.read(1010), "أَلف و عَشَرَة")
        XCTAssertEqual(arabic.read(1011), "أَلف و أَحَدَ عَشَرَ")
        XCTAssertEqual(arabic.read(1012), "أَلف و اِثْنَا عَشَرَ")
        XCTAssertEqual(arabic.read(1022), "أَلف و اِثْنَان و عِشْرُونَ")
        XCTAssertEqual(arabic.read(1099), "أَلف و تِسْعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(1100), "أَلف و مِئَة")
        XCTAssertEqual(arabic.read(1101), "أَلف و مِئَة و وَاحِد")
        XCTAssertEqual(arabic.read(1102), "أَلف و مِئَة و اِثْنَان")
        XCTAssertEqual(arabic.read(1199), "أَلف و مِئَة و تِسْعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(1234), "أَلف و مِا۟ئَتَان و أَرْبَعَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(2000), "أَلفين")
        XCTAssertEqual(arabic.read(1021), "أَلف و وَاحِد و عِشْرُونَ")
        XCTAssertEqual(arabic.read(3000), "ثَلَاثَة أَلاف")
        XCTAssertEqual(arabic.read(3021), "ثَلَاثَة أَلاف و وَاحِد و عِشْرُونَ")
        XCTAssertEqual(arabic.read(4000), "أَرْبَعَة أَلاف")
        XCTAssertEqual(arabic.read(4131), "أَرْبَعَة أَلاف و مِئَة و وَاحِد و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(5000), "خَمْسَة أَلاف")
        XCTAssertEqual(arabic.read(5333), "خَمْسَة أَلاف و ثَلَاثُمِئَة و ثَلَاثَة و ثَلَاثُونَ")
        XCTAssertEqual(arabic.read(6000), "سِتَّة أَلاف")
        XCTAssertEqual(arabic.read(6456), "سِتَّة أَلاف و أَرْبَعُمِئَة و سِتَّة و خَمْسُونَ")
        XCTAssertEqual(arabic.read(7000), "سَبْعَة أَلاف")
        XCTAssertEqual(arabic.read(7021), "سَبْعَة أَلاف و وَاحِد و عِشْرُونَ")
        XCTAssertEqual(arabic.read(8000), "ثَمَانِيَة أَلاف")
        XCTAssertEqual(arabic.read(8881), "ثَمَانِيَة أَلاف و ثَمَانِيُمِئَة و وَاحِد و ثَمَانُونَ")
        XCTAssertEqual(arabic.read(9000), "تِسْعَة أَلاف")
        XCTAssertEqual(arabic.read(9999), "تِسْعَة أَلاف و تِسْعُمِئَة و تِسْعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(10_000), "عَشَرَة أَلاف")
        XCTAssertEqual(arabic.read(10_021), "عَشَرَة أَلاف و وَاحِد و عِشْرُونَ")
        XCTAssertEqual(arabic.read(234_566), "مِا۟ئَتَان و أَرْبَعَة و ثَلَاثُونَ أَلاف و خُمْسُمِئَة و سِتَّة و سِتُّونَ")
        XCTAssertEqual(arabic.read(999_999), "تِسْعُمِئَة و تِسْعَة و تِسْعُونَ أَلاف و تِسْعُمِئَة و تِسْعَة و تِسْعُونَ")
        XCTAssertEqual(arabic.read(1_000_000), "مليون")
        
        /// chat GTP
        XCTAssertEqual(arabic.read(1_000_000), "مليون")
        XCTAssertEqual(arabic.read(2_000_000), "اثنان مليون")
        XCTAssertEqual(arabic.read(3_000_000), "ثلاثة مليون")
        XCTAssertEqual(arabic.read(4_000_000), "أربعة مليون")
        XCTAssertEqual(arabic.read(5_000_000), "خمسة مليون")
        XCTAssertEqual(arabic.read(6_000_000), "ستة مليون")
        XCTAssertEqual(arabic.read(7_000_000), "سبعة مليون")
        XCTAssertEqual(arabic.read(8_000_000), "ثمانية مليون")
        XCTAssertEqual(arabic.read(9_000_000), "تسعة مليون")
        XCTAssertEqual(arabic.read(10_000_000), "عشرة مليون")
        XCTAssertEqual(arabic.read(11_000_000), "أحد عشر مليون")
        XCTAssertEqual(arabic.read(12_000_000), "اثنا عشر مليون")
        XCTAssertEqual(arabic.read(13_000_000), "ثلاثة عشر مليون")
        XCTAssertEqual(arabic.read(14_000_000), "أربعة عشر مليون")
        XCTAssertEqual(arabic.read(15_000_000), "خمسة عشر مليون")
        
        XCTAssertEqual(arabic.read(2_000_000), "مليونان")
        XCTAssertEqual(arabic.read(3_000_000), "ثلاثة ملايين")
        XCTAssertEqual(arabic.read(3_000_000), "ثلاثة ملايين")
        XCTAssertEqual(arabic.read(5_000_000), "خمسة ملايين")
        XCTAssertEqual(arabic.read(1_755_830), "مليون وسبع مئة وخمسة وخمسون ألفاً وثمان مئة وثلاثون")
        XCTAssertEqual(arabic.read(5_800_130), "خمسة ملايين وثمان مئة ألف ومئة وثلاثون")
        XCTAssertEqual(arabic.read(1_960_320_000), "مليار وتسع مئة وستون مليوناً وثلاث مئة وعشرون ألفاً")
        XCTAssertEqual(arabic.read(3_600_123_990), "ثلاثة مليارات وستة ملايين ومئة وثلاثة وعشرون ألفاً وتسع مئة وتسعون")
        XCTAssertEqual(arabic.read(30_000_000_000), "ثلاثون مِلْيار")
        
    }
    
    func XXtest_chatGPT() {
        let tests = """
        60@ستون
        70@سبعون
        80@ثمانون
        90@تسعون
        """
let _ = """
0@صفر
1@واحد
2@اثنان
3@ثلاثة
4@أربعة
5@خمسة
6@ستة
7@سبعة
8@ثمانية
9@تسعة
10@عشرة
11@أحد عشر
12@اثنا عشر
13@ثلاثة عشر
14@أربعة عشر
15@خمسة عشر
16@ستة عشر
17@سبعة عشر
18@ثمانية عشر
19@تسعة عشر
20@عشرون
21@واحد وعشرون
22@اثنان وعشرون
23@ثلاثة وعشرون
24@أربعة وعشرون
25@خمسة وعشرون
26@ستة وعشرون
27@سبعة وعشرون
28@ثمانية وعشرون
29@تسعة وعشرون
30@ثلاثون
31@واحد وثلاثون
32@اثنان وثلاثون
33@ثلاثة وثلاثون
34@أربعة وثلاثون
35@خمسة وثلاثون
36@ستة وثلاثون
37@سبعة وثلاثون
38@ثمانية وثلاثون
39@تسعة وثلاثون
40@أربعون
41@واحد وأربعون
42@اثنان وأربعون
43@ثلاثة وأربعون
44@أربعة وأربعون
45@خمسة وأربعون
46@ستة وأربعون
47@سبعة وأربعون
48@ثمانية وأربعون
49@تسعة وأربعون
50@خمسون
91@واحد وتسعون
92@اثنان وتسعون
93@ثلاثة وتسعون
94@أربعة وتسعون
95@خمسة وتسعون
96@ستة وتسعون
97@سبعة وتسعون
98@ثمانية وتسعون
99@تسعة وتسعون
100@مئة
101@مئة وواحد
102@مئة واثنان
103@مئة وثلاثة
104@مئة وأربعة
105@مئة وخمسة
106@مئة وستة
107@مئة وسبعة
108@مئة وثمانية
109@مئة وتسعة
110@مئة وعشرة
111@مئة وأحد عشر
112@مئة واثنا عشر
200@مئتان
201@مئتان وواحد
202@مئتان واثنان
203@مئتان وثلاثة
204@مئتان وأربعة
205@مئتان وخمسة
206@مئتان وستة
207@مئتان وسبعة
208@مئتان وثمانية
209@مئتان وتسعة
210@مئتان وعشرة
211@مئتان وأحد عشر
212@مئتان واثنا عشر
213@مئتان وثلاثة عشر
214@مئتان وأربعة عشر
297@مئتان وسبعة وتسعون
305@ثلاثمئة وخمسة
313@ثلاثمئة وثلاثة عشر
321@ثلاثمئة وواحد وعشرون
329@ثلاثمئة وتسعة وعشرون
337@أربعمئة وسبعة وثلاثون
345@أربعمئة وخمسة وأربعون
353@أربعمئة وثلاثة وخمسون
361@أربعمئة وواحد وستون
369@أربعمئة وتسعة وستون
377@خمسمئة وسبعة وسبعون
385@خمسمئة وخمسة وثمانون
393@خمسمئة وثلاثة وتسعون
401@ستمئة وواحد
409@ستمئة وتسعة
417@سبعمئة وسبعة عشر
425@سبعمئة وخمسة وعشرون
433@ثمانمئة وثلاثة وثلاثون
441@ثمانمئة وواحد وأربعون
449@تسعمئة وتسعة وأربعون
457@تسعمئة وسبعة وخمسون
465@ألف وخمسمئة وخمسة وستون
473@ألف وخمسمئة وثلاثة وسبعون
481@ألف وخمسمئة وواحد وثمانون
489@ألف وخمسمئة وتسعة وثمانون
497@ألف وسبعمئة وسبعة وتسعون
505@ألف وسبعمئة وخمسة
513@ألف وسبعمئة وثلاثة عشر
521@ألف وسبعمئة وواحد وعشرون
529@ألف وسبعمئة وتسعة وعشرون
537@ألف وثمانمئة وسبعة وثلاثون
545@ألف وثمانمئة وخمسة وأربعون
553@ألف وثمانمئة وثلاثة وخمسون
561@ألف وثمانمئة وواحد وستون
569@ألف وثمانمئة وتسعة وستون
577@ألف وتسعمئة وسبعة وسبعون
585@ألف وتسعمئة وخمسة وثمانون
593@ألف وتسعمئة وثلاثة وتسعون
601@ألف وستمئة وواحد
609@ألف وستمئة وتسعة
617@ألف وسبعمئة وسبعة عشر
625@ألف وسبعمئة وخمسة وعشرون
633@ألف وثمانمئة وثلاثة وثلاثون
641@ألف وثمانمئة وواحد وأربعون
649@ألف وتسعمئة وتسعة وأربعون
657@ألف وتسعمئة وسبعة وخمسون
665@ألف وستمئة وخمسة و
700@سبعمئة
800@ثمانمئة
900@تسعمئة
997@تسعمئة وسبعة وتسعون
1005@ألف وخمسمئة وخمسة
1013@ألف وخمسمئة وثلاثة عشر
1021@ألف وخمسمئة وواحد وعشرون
1029@ألف وخمسمئة وتسعة وعشرون
1037@ألف وستمئة وسبعة وثلاثون
1045@ألف وستمئة وخمسة وأربعون
1053@ألف وستمئة وثلاثة وخمسون
1061@ألف وستمئة وواحد وستون
1069@ألف وستمئة وتسعة وستون
1077@ألف وسبعمئة وسبعة وسبعون
1085@ألف وسبعمئة وخمسة وثمانون
1093@ألف وسبعمئة وثلاثة وتسعون
1101@ألف وستمئة وواحد
1109@ألف وستمئة وتسعة
1115@ألف ومئة وخمسة عشر
2000@ألفين
3000@ثلاثة آلاف
4000@أربعة آلاف
5000@خمسة آلاف
6000@ستة آلاف
7000@سبعة آلاف
8000@ثمانية آلاف
9000@تسعة آلاف
10000@عشرة آلاف
100000@مئة ألف
1000000@مليون
2000000@مليونين
3000000@ثلاثة ملايين
4000000@أربعة ملايين
10000000@عشرة ملايين
100000000@مئة مليون
1000000000@مليار
1000000000000@تريليون
"""
        let max = 3000000
        var count = 0
        let lines = tests.components(separatedBy: "\n")
        for line in lines {
            let components = line.components(separatedBy: "@")
            if count < max {
                print("        XCTAssertEqual(arabic.read("+components[0]+"), \""+components[1]+"\")")
            }
            count += 1
        }
        print("done")
    }
    
}
