//
//  Test_Spanish.swift
//  TranslateNumbersTests
//
//  Created by Joachim Neumann on 12/14/23.
//

import XCTest

final class Test_Spanish: XCTestCase {
    func test_spanish() {
        let spanish = Languages().spanish
        
        XCTAssertEqual(spanish.read(-1), "menos uno")
        XCTAssertEqual(spanish.read(-1), "menos uno")
        XCTAssertEqual(spanish.read("1.5"), "uno coma cinco")
        XCTAssertEqual(spanish.read("-1.5"), "menos uno coma cinco")
        XCTAssertEqual(spanish.read("-1.51"), "menos uno coma cinco uno")
        XCTAssertEqual(spanish.read("-0.7"), "menos cero coma siete")
        XCTAssertEqual(spanish.read("-1.5"), "menos uno coma cinco")
        XCTAssertEqual(spanish.read(0), "cero")
        XCTAssertEqual(spanish.read(1), "uno")
        XCTAssertEqual(spanish.read(2), "dos")
        XCTAssertEqual(spanish.read(3), "tres")
        XCTAssertEqual(spanish.read(4), "cuatro")
        XCTAssertEqual(spanish.read(5), "cinco")
        XCTAssertEqual(spanish.read(6), "seis")
        XCTAssertEqual(spanish.read(7), "siete")
        XCTAssertEqual(spanish.read(8), "ocho")
        XCTAssertEqual(spanish.read(9), "nueve")
        XCTAssertEqual(spanish.read(10), "diez")
        XCTAssertEqual(spanish.read(11), "once")
        XCTAssertEqual(spanish.read(12), "doce")
        XCTAssertEqual(spanish.read(13), "trece")
        XCTAssertEqual(spanish.read(14), "catorce")
        XCTAssertEqual(spanish.read(15), "quince")
        XCTAssertEqual(spanish.read(16), "dieciséis")
        XCTAssertEqual(spanish.read(17), "diecisiete")
        XCTAssertEqual(spanish.read(18), "dieciocho")
        XCTAssertEqual(spanish.read(19), "diecinueve")
        XCTAssertEqual(spanish.read(20), "veinte")
        XCTAssertEqual(spanish.read(21), "veintiuno")
        XCTAssertEqual(spanish.read(22), "veintidós")
        XCTAssertEqual(spanish.read(23), "veintitrés")
        XCTAssertEqual(spanish.read(24), "veinticuatro")
        XCTAssertEqual(spanish.read(25), "veinticinco")
        XCTAssertEqual(spanish.read(26), "veintiséis")
        XCTAssertEqual(spanish.read(27), "veintisiete")
        XCTAssertEqual(spanish.read(28), "veintiocho")
        XCTAssertEqual(spanish.read(29), "veintinueve")
        XCTAssertEqual(spanish.read(20), "veinte")
        XCTAssertEqual(spanish.read(31), "treinta y uno")
        XCTAssertEqual(spanish.read(32), "treinta y dos")
        XCTAssertEqual(spanish.read(33), "treinta y tres")
        XCTAssertEqual(spanish.read(34), "treinta y cuatro")
        XCTAssertEqual(spanish.read(35), "treinta y cinco")
        XCTAssertEqual(spanish.read(36), "treinta y seis")
        XCTAssertEqual(spanish.read(37), "treinta y siete")
        XCTAssertEqual(spanish.read(38), "treinta y ocho")
        XCTAssertEqual(spanish.read(39), "treinta y nueve")
        XCTAssertEqual(spanish.read(40), "cuarenta")
        XCTAssertEqual(spanish.read(41), "cuarenta y uno")
        XCTAssertEqual(spanish.read(42), "cuarenta y dos")
        XCTAssertEqual(spanish.read(43), "cuarenta y tres")
        XCTAssertEqual(spanish.read(44), "cuarenta y cuatro")
        XCTAssertEqual(spanish.read(45), "cuarenta y cinco")
        XCTAssertEqual(spanish.read(46), "cuarenta y seis")
        XCTAssertEqual(spanish.read(47), "cuarenta y siete")
        XCTAssertEqual(spanish.read(48), "cuarenta y ocho")
        XCTAssertEqual(spanish.read(49), "cuarenta y nueve")
        XCTAssertEqual(spanish.read(50), "cincuenta")
        XCTAssertEqual(spanish.read(51), "cincuenta y uno")
        XCTAssertEqual(spanish.read(52), "cincuenta y dos")
        XCTAssertEqual(spanish.read(53), "cincuenta y tres")
        XCTAssertEqual(spanish.read(54), "cincuenta y cuatro")
        XCTAssertEqual(spanish.read(55), "cincuenta y cinco")
        XCTAssertEqual(spanish.read(56), "cincuenta y seis")
        XCTAssertEqual(spanish.read(57), "cincuenta y siete")
        XCTAssertEqual(spanish.read(58), "cincuenta y ocho")
        XCTAssertEqual(spanish.read(59), "cincuenta y nueve")
        XCTAssertEqual(spanish.read(60), "sesenta")
        XCTAssertEqual(spanish.read(61), "sesenta y uno")
        XCTAssertEqual(spanish.read(62), "sesenta y dos")
        XCTAssertEqual(spanish.read(63), "sesenta y tres")
        XCTAssertEqual(spanish.read(64), "sesenta y cuatro")
        XCTAssertEqual(spanish.read(65), "sesenta y cinco")
        XCTAssertEqual(spanish.read(66), "sesenta y seis")
        XCTAssertEqual(spanish.read(67), "sesenta y siete")
        XCTAssertEqual(spanish.read(68), "sesenta y ocho")
        XCTAssertEqual(spanish.read(69), "sesenta y nueve")
        XCTAssertEqual(spanish.read(70), "setenta")
        XCTAssertEqual(spanish.read(71), "setenta y uno")
        XCTAssertEqual(spanish.read(72), "setenta y dos")
        XCTAssertEqual(spanish.read(73), "setenta y tres")
        XCTAssertEqual(spanish.read(74), "setenta y cuatro")
        XCTAssertEqual(spanish.read(75), "setenta y cinco")
        XCTAssertEqual(spanish.read(76), "setenta y seis")
        XCTAssertEqual(spanish.read(77), "setenta y siete")
        XCTAssertEqual(spanish.read(78), "setenta y ocho")
        XCTAssertEqual(spanish.read(79), "setenta y nueve")
        XCTAssertEqual(spanish.read(80), "ochenta")
        XCTAssertEqual(spanish.read(81), "ochenta y uno")
        XCTAssertEqual(spanish.read(82), "ochenta y dos")
        XCTAssertEqual(spanish.read(83), "ochenta y tres")
        XCTAssertEqual(spanish.read(84), "ochenta y cuatro")
        XCTAssertEqual(spanish.read(85), "ochenta y cinco")
        XCTAssertEqual(spanish.read(86), "ochenta y seis")
        XCTAssertEqual(spanish.read(87), "ochenta y siete")
        XCTAssertEqual(spanish.read(88), "ochenta y ocho")
        XCTAssertEqual(spanish.read(89), "ochenta y nueve")
        XCTAssertEqual(spanish.read(90), "noventa")
        XCTAssertEqual(spanish.read(91), "noventa y uno")
        XCTAssertEqual(spanish.read(92), "noventa y dos")
        XCTAssertEqual(spanish.read(93), "noventa y tres")
        XCTAssertEqual(spanish.read(94), "noventa y cuatro")
        XCTAssertEqual(spanish.read(95), "noventa y cinco")
        XCTAssertEqual(spanish.read(96), "noventa y seis")
        XCTAssertEqual(spanish.read(97), "noventa y siete")
        XCTAssertEqual(spanish.read(98), "noventa y ocho")
        XCTAssertEqual(spanish.read(99), "noventa y nueve")
        XCTAssertEqual(spanish.read(100), "cien")
        XCTAssertEqual(spanish.read(101), "ciento uno")
        XCTAssertEqual(spanish.read(102), "ciento dos")
        XCTAssertEqual(spanish.read(103), "ciento tres")
        XCTAssertEqual(spanish.read(104), "ciento cuatro")
        XCTAssertEqual(spanish.read(105), "ciento cinco")
        XCTAssertEqual(spanish.read(106), "ciento seis")
        XCTAssertEqual(spanish.read(107), "ciento siete")
        XCTAssertEqual(spanish.read(108), "ciento ocho")
        XCTAssertEqual(spanish.read(109), "ciento nueve")
        XCTAssertEqual(spanish.read(110), "ciento diez")
        XCTAssertEqual(spanish.read(111), "ciento once")
        XCTAssertEqual(spanish.read(112), "ciento doce")
        XCTAssertEqual(spanish.read(113), "ciento trece")
        XCTAssertEqual(spanish.read(119), "ciento diecinueve")
        XCTAssertEqual(spanish.read(120), "ciento veinte")
        XCTAssertEqual(spanish.read(121), "ciento veintiuno")
        XCTAssertEqual(spanish.read(122), "ciento veintidós")
        XCTAssertEqual(spanish.read(190), "ciento noventa")
        XCTAssertEqual(spanish.read(144), "ciento cuarenta y cuatro")
        XCTAssertEqual(spanish.read(200), "doscientos")
        XCTAssertEqual(spanish.read(211), "doscientos once")
        XCTAssertEqual(spanish.read(300), "trescientos")
        XCTAssertEqual(spanish.read(400), "cuatrocientos")
        XCTAssertEqual(spanish.read(500), "quinientos")
        XCTAssertEqual(spanish.read(600), "seiscientos")
        XCTAssertEqual(spanish.read(700), "setecientos")
        XCTAssertEqual(spanish.read(706), "setecientos seis")
        XCTAssertEqual(spanish.read(726), "setecientos veintiséis")
        XCTAssertEqual(spanish.read(800), "ochocientos")
        XCTAssertEqual(spanish.read(900), "novecientos")
        XCTAssertEqual(spanish.read(1_000), "mil")
        XCTAssertEqual(spanish.read(2_000), "dos mil")
        XCTAssertEqual(spanish.read(3_000), "tres mil")
        XCTAssertEqual(spanish.read(3_001), "tres mil uno")
        XCTAssertEqual(spanish.read(6_000), "seis mil")
        XCTAssertEqual(spanish.read(6_001), "seis mil uno")
        XCTAssertEqual(spanish.read(10_000), "diez mil")
        XCTAssertEqual(spanish.read(11_001), "once mil uno")
        XCTAssertEqual(spanish.read(12_895), "doce mil ochocientos noventa y cinco")
        XCTAssertEqual(spanish.read(12_786), "doce mil setecientos ochenta y seis")
        XCTAssertEqual(spanish.read(70_000), "setenta mil")
        XCTAssertEqual(spanish.read(187_372), "ciento ochenta y siete mil trescientos setenta y dos")
        XCTAssertEqual(spanish.read(200_000), "doscientos mil")
        XCTAssertEqual(spanish.read(280_065), "doscientos ochenta mil sesenta y cinco")
        XCTAssertEqual(spanish.read(706_210), "setecientos seis mil doscientos diez")
        XCTAssertEqual(spanish.read(100_000), "cien mil")
        XCTAssertEqual(spanish.read(1_000_000), "un millón")
        XCTAssertEqual(spanish.read(1_000_050), "un millón cincuenta")
        XCTAssertEqual(spanish.read(3_000_100), "tres millones cien")
        XCTAssertEqual(spanish.read(10_000_000), "diez millones")
        XCTAssertEqual(spanish.read(40_000_000), "cuarenta millones")
        XCTAssertEqual(spanish.read(62_000_000), "sesenta y dos millones")
        XCTAssertEqual(spanish.read(62_003_005), "sesenta y dos millones tres mil cinco")
        XCTAssertEqual(spanish.read(62_003_105), "sesenta y dos millones tres mil ciento cinco")
        XCTAssertEqual(spanish.read(100_000_000), "cien millones")
        XCTAssertEqual(spanish.read(500_000_000), "quinientos millones")
        XCTAssertEqual(spanish.read(1_000_000_000), "mil millones")
        XCTAssertEqual(spanish.read(1_000_000_200), "mil millones doscientos")
        XCTAssertEqual(spanish.read(10_000_000_000), "diez mil millones")
        XCTAssertEqual(spanish.read(20_000_000_700), "veinte mil millones setecientos")
        XCTAssertEqual(spanish.read(100_000_000_000), "cien mil millones")
        XCTAssertEqual(spanish.read(400_000_000_000), "cuatrocientos mil millones")
        XCTAssertEqual(spanish.read(1_000_000_000_000), "un billón")
        XCTAssertEqual(spanish.read(3_000_000_000_000), "tres billiones")

        XCTAssertEqual(spanish.read(-1), "menos uno")
        XCTAssertEqual(spanish.read(-74), "menos setenta y cuatro")
        XCTAssertEqual(spanish.read(-1_000_000), "menos un millón")
        XCTAssertEqual(spanish.read("3.1415926"), "tres coma uno cuatro uno cinco nueve dos seis")
        XCTAssertEqual(spanish.read("-3.1415926"), "menos tres coma uno cuatro uno cinco nueve dos seis")
        XCTAssertEqual(spanish.read("3.4e16"), "tres coma cuatro por diez elevado a dieciséis")
        XCTAssertEqual(spanish.read("3.5e26"), "tres coma cinco por diez elevado a veintiséis")
    }
}
