//
// Test_Chinese.swift
// TranslateNumbers
//
// Created by Joachim Neumann on1 2/18/23.
//

import XCTest

final class TestChinese: XCTestCase {
    let simplified  = Languages().chineseSimplified
    let traditional = Languages().chineseTraditional
    let financial   = Languages().chineseFinancial
    
    func test_traditional() {
        XCTAssertEqual(traditional.read(0), "零")
        XCTAssertEqual(traditional.read(10_000), "一萬")
        XCTAssertEqual(traditional.read(789_0298), "七百 八十九萬 零二百 九十八")
    }
    
    func test_financial() {
        XCTAssertEqual(financial.read(0), "零")
        XCTAssertEqual(financial.read(1), "壹")
        XCTAssertEqual(financial.read(2), "壹")
        XCTAssertEqual(financial.read(3), "叁")
        XCTAssertEqual(financial.read(4), "肆")
        XCTAssertEqual(financial.read(5), "伍")
        XCTAssertEqual(financial.read(6), "陆")
        XCTAssertEqual(financial.read(7), "柒")
        XCTAssertEqual(financial.read(8), "捌")
        XCTAssertEqual(financial.read(9), "玖")
        XCTAssertEqual(financial.read(10), "拾")
        XCTAssertEqual(financial.read(11), "拾壹")
        XCTAssertEqual(financial.read(10_000), "壹萬")
    }
    
    func test_simplified() {
        ///https://www.mezzoguild.com/learn/chinese/numbers/
        XCTAssertEqual(simplified.read(0), "〇")
        XCTAssertEqual(simplified.read(1), "一")
        XCTAssertEqual(simplified.read(2), "二")
        XCTAssertEqual(simplified.read(3), "三")
        XCTAssertEqual(simplified.read(4), "四")
        XCTAssertEqual(simplified.read(5), "五")
        XCTAssertEqual(simplified.read(6), "六")
        XCTAssertEqual(simplified.read(7), "七")
        XCTAssertEqual(simplified.read(8), "八")
        XCTAssertEqual(simplified.read(9), "九")
        XCTAssertEqual(simplified.read(10), "十")
        XCTAssertEqual(simplified.read(11), "十一")
        XCTAssertEqual(simplified.read(12), "十二")
        XCTAssertEqual(simplified.read(13), "十三")
        XCTAssertEqual(simplified.read(14), "十四")
        XCTAssertEqual(simplified.read(15), "十五")
        XCTAssertEqual(simplified.read(16), "十六")
        XCTAssertEqual(simplified.read(17), "十七")
        XCTAssertEqual(simplified.read(18), "十八")
        XCTAssertEqual(simplified.read(19), "十九")
        XCTAssertEqual(simplified.read(20), "二十")
        XCTAssertEqual(simplified.read(30), "三十")
        XCTAssertEqual(simplified.read(32), "三十二")
        XCTAssertEqual(simplified.read(50), "五十")
        XCTAssertEqual(simplified.read(54), "五十四")
        XCTAssertEqual(simplified.read(78), "七十八")
        XCTAssertEqual(simplified.read(98), "九十八")
        XCTAssertEqual(simplified.read(99), "九十九")
        XCTAssertEqual(simplified.read(100), "一百")
        XCTAssertEqual(simplified.read(101), "一百 零一")
        XCTAssertEqual(simplified.read(102), "一百 零二")
        XCTAssertEqual(simplified.read(103), "一百 零三")
        XCTAssertEqual(simplified.read(104), "一百 零四")
        XCTAssertEqual(simplified.read(110), "一百 一十")
        XCTAssertEqual(simplified.read(111), "一百 一十一")
        XCTAssertEqual(simplified.read(112), "一百 一十二")
        XCTAssertEqual(simplified.read(113), "一百 一十三")
        XCTAssertEqual(simplified.read(120), "一百 二十")
        XCTAssertEqual(simplified.read(130), "一百 三十")
        XCTAssertEqual(simplified.read(140), "一百 四十")
        XCTAssertEqual(simplified.read(125), "一百 二十五")
        XCTAssertEqual(simplified.read(132), "一百 三十二")
        XCTAssertEqual(simplified.read(147), "一百 四十七")
        XCTAssertEqual(simplified.read(152), "一百 五十二")
        XCTAssertEqual(simplified.read(166), "一百 六十六")
        XCTAssertEqual(simplified.read(178), "一百 七十八")
        XCTAssertEqual(simplified.read(183), "一百 八十三")
        XCTAssertEqual(simplified.read(197), "一百 九十七")
        XCTAssertEqual(simplified.read(200), "二百")
        XCTAssertEqual(simplified.read(208), "二百 零八")
        XCTAssertEqual(simplified.read(300), "三百")
        XCTAssertEqual(simplified.read(305), "三百 零五")
        XCTAssertEqual(simplified.read(400), "四百")
        XCTAssertEqual(simplified.read(432), "四百 三十二")
        XCTAssertEqual(simplified.read(500), "五百")
        XCTAssertEqual(simplified.read(600), "六百")
        XCTAssertEqual(simplified.read(700), "七百")
        XCTAssertEqual(simplified.read(800), "八百")
        XCTAssertEqual(simplified.read(900), "九百")
        XCTAssertEqual(simplified.read(301), "三百 零一")
        XCTAssertEqual(simplified.read(565), "五百 六十五")
        XCTAssertEqual(simplified.read(732), "七百 三十二")
        XCTAssertEqual(simplified.read(890), "八百 九十")
        XCTAssertEqual(simplified.read(945), "九百 四十五")
        XCTAssertEqual(simplified.read(1000), "一千")
        XCTAssertEqual(simplified.read(1001), "一千 零一")
        XCTAssertEqual(simplified.read(1003), "一千 零三")
        XCTAssertEqual(simplified.read(1005), "一千 零五")
        XCTAssertEqual(simplified.read(1006), "一千 零六")
        XCTAssertEqual(simplified.read(1010), "一千 零一十")
        XCTAssertEqual(simplified.read(1020), "一千 零二十")
        XCTAssertEqual(simplified.read(1035), "一千 零三十五")
        XCTAssertEqual(simplified.read(1100), "一千 一百")
        XCTAssertEqual(simplified.read(1111), "一千 一百 一十一")
        XCTAssertEqual(simplified.read(1200), "一千 二百")
        XCTAssertEqual(simplified.read(1234), "一千 二百 三十四")
        XCTAssertEqual(simplified.read(1999), "一千 九百 九十九")
        XCTAssertEqual(simplified.read(2000), "二千")
        XCTAssertEqual(simplified.read(2001), "二千 零一")
        XCTAssertEqual(simplified.read(2010), "二千 零一十")
        XCTAssertEqual(simplified.read(2345), "二千 三百 四十五")
        XCTAssertEqual(simplified.read(3000), "三千")
        XCTAssertEqual(simplified.read(3454), "三千 四百 五十四")
        XCTAssertEqual(simplified.read(4000), "四千")
        XCTAssertEqual(simplified.read(5000), "五千")
        XCTAssertEqual(simplified.read(6000), "六千")
        XCTAssertEqual(simplified.read(7000), "七千")
        XCTAssertEqual(simplified.read(7045), "七千 零四十五")
        XCTAssertEqual(simplified.read(8000), "八千")
        XCTAssertEqual(simplified.read(9000), "九千")
        
        XCTAssertEqual(simplified.read(1_0000), "一万")
        XCTAssertEqual(simplified.read(1_0001), "一万 零一")
        XCTAssertEqual(simplified.read(1_0003), "一万 零三")
        XCTAssertEqual(simplified.read(1_0101), "一万 零一百 零一")
        XCTAssertEqual(simplified.read(1_0207), "一万 零二百 零七")
        XCTAssertEqual(simplified.read(1_0509), "一万 零五百 零九")
        XCTAssertEqual(simplified.read(1_1000), "一万 一千")
        XCTAssertEqual(simplified.read(1_1050), "一万 一千 零五十")
        XCTAssertEqual(simplified.read(1_1500), "一万 一千 五百")
        XCTAssertEqual(simplified.read(1_1741), "一万 一千 七百 四十一")
        XCTAssertEqual(simplified.read(1_2000), "一万 二千")
        XCTAssertEqual(simplified.read(1_2345), "一万 二千 三百 四十五")
        XCTAssertEqual(simplified.read(1_3200), "一万 三千 二百")
        XCTAssertEqual(simplified.read(1_8000), "一万 八千")
        XCTAssertEqual(simplified.read(2_0000), "二万")
        XCTAssertEqual(simplified.read(2_3456), "二万 三千 四百 五十六")
        XCTAssertEqual(simplified.read(3_1240), "三万 一千 二百 四十")
        XCTAssertEqual(simplified.read(4_0000), "四万")
        XCTAssertEqual(simplified.read(4_0005), "四万 零五")
        XCTAssertEqual(simplified.read(4_0050), "四万 零五十")
        XCTAssertEqual(simplified.read(4_0500), "四万 零五百")
        XCTAssertEqual(simplified.read(4_5000), "四万 五千")
        XCTAssertEqual(simplified.read(5_0555), "五万 零五百 五十五")
        XCTAssertEqual(simplified.read(5_2152), "五万 二千 一百 五十二")
        XCTAssertEqual(simplified.read(5_6700), "五万 六千 七百")
        XCTAssertEqual(simplified.read(10_0000), "十万")
        XCTAssertEqual(simplified.read(10_0070), "十万 零七十")
        XCTAssertEqual(simplified.read(10_0222), "十万 零二百 二十二")
        XCTAssertEqual(simplified.read(10_1010), "十万 一千 零一十")
        XCTAssertEqual(simplified.read(11_0000), "十一万")
        XCTAssertEqual(simplified.read(12_3446), "十二万 三千 四百 四十六")
        XCTAssertEqual(simplified.read(20_0000), "二十万")
        XCTAssertEqual(simplified.read(20_0300), "二十万 零三百")
        XCTAssertEqual(simplified.read(21_4000), "二十一万 四千")
        XCTAssertEqual(simplified.read(30_0000), "三十万")
        XCTAssertEqual(simplified.read(30_0250), "三十万 零二百 五十")
        XCTAssertEqual(simplified.read(56_7000), "五十六万 七千")
        XCTAssertEqual(simplified.read(76_5432), "七十六万 五千 四百 三十二")
        XCTAssertEqual(simplified.read(100_0000), "一百万")
        XCTAssertEqual(simplified.read(100_0001), "一百万 零一")
        XCTAssertEqual(simplified.read(100_0010), "一百万 零一十")
        XCTAssertEqual(simplified.read(100_0100), "一百万 零一百")
        XCTAssertEqual(simplified.read(100_1000), "一百万 一千")
        XCTAssertEqual(simplified.read(101_0000), "一百 零一万")
        XCTAssertEqual(simplified.read(101_0101), "一百 零一万 零一百 零一")
        XCTAssertEqual(simplified.read(110_0000), "一百 一十万")
        XCTAssertEqual(simplified.read(112_3456), "一百 一十二万 三千 四百 五十六")
        XCTAssertEqual(simplified.read(162_8333), "一百 六十二万 八千 三百 三十三")
        XCTAssertEqual(simplified.read(291_4680), "二百 九十一万 四千 六百 八十")
        XCTAssertEqual(simplified.read(600_9123), "六百万 九千 一百 二十三")
        XCTAssertEqual(simplified.read(608_9123), "六百 零八万 九千 一百 二十三")
        XCTAssertEqual(simplified.read(670_0123), "六百 七十万 零一百 二十三")
        XCTAssertEqual(simplified.read(670_9123), "六百 七十万 九千 一百 二十三")
        XCTAssertEqual(simplified.read(678_9003), "六百 七十八万 九千 零三")
        XCTAssertEqual(simplified.read(678_9123), "六百 七十八万 九千 一百 二十三")
        XCTAssertEqual(simplified.read(678_9100), "六百 七十八万 九千 一百")
        XCTAssertEqual(simplified.read(678_9120), "六百 七十八万 九千 一百 二十")
        XCTAssertEqual(simplified.read(678_0023), "六百 七十八万 零二十三")
        XCTAssertEqual(simplified.read(700_0000), "七百万")
        XCTAssertEqual(simplified.read(789_0000), "七百 八十九万")
        XCTAssertEqual(simplified.read(789_0298), "七百 八十九万 零二百 九十八")
        XCTAssertEqual(simplified.read(800_0000), "八百万")
        XCTAssertEqual(simplified.read(800_0300), "八百万 零三百")
        XCTAssertEqual(simplified.read(1000_0000), "一千万")
        XCTAssertEqual(simplified.read(1010_1010), "一千 零一十万 一千 零一十")
        XCTAssertEqual(simplified.read(2700_0000), "二千 七百万")
        XCTAssertEqual(simplified.read(2721_4000), "二千 七百 二十一万 四千")
        XCTAssertEqual(simplified.read(2721_4896), "二千 七百 二十一万 四千 八百 九十六")
        XCTAssertEqual(simplified.read(2772_1000), "二千 七百 七十二万 一千")
        XCTAssertEqual(simplified.read(3456_7890), "三千 四百 五十六万 七千 八百 九十")
        XCTAssertEqual(simplified.read(5379_8250), "五千 三百 七十九万 八千 二百 五十")
        XCTAssertEqual(simplified.read(9800_0000), "九千 八百万")
        XCTAssertEqual(simplified.read(9876_5000), "九千 八百 七十六万 五千")
        XCTAssertEqual(simplified.read(9876_5432), "九千 八百 七十六万 五千 四百 三十二")
        XCTAssertEqual(simplified.read(1_0000_0000), "一亿")
        XCTAssertEqual(simplified.read(1_0101_0101), "一亿 零一百 零一万 零一百 零一")
        XCTAssertEqual(simplified.read(1_2345_6789), "一亿 二千 三百 四十五万 六千 七百 八十九")
        XCTAssertEqual(simplified.read(2_0080_0000), "二亿 零八十万")
        XCTAssertEqual(simplified.read(2_4050_0000), "二亿 四千 零五十万")
        XCTAssertEqual(simplified.read(3_0000_0000), "三亿")
        XCTAssertEqual(simplified.read(4_1429_4182), "四亿 一千 四百 二十九万 四千 一百 八十二")
        XCTAssertEqual(simplified.read(10_0000_0000), "十亿")
        XCTAssertEqual(simplified.read(10_1010_1010), "十亿 一千 零一十万 一千 零一十")
        XCTAssertEqual(simplified.read(12_0008_0000), "十二亿 零八万")
        XCTAssertEqual(simplified.read(13_2680_0000), "十三亿 二千 六百 八十万")
        XCTAssertEqual(simplified.read(98_7654_3210), "九十八亿 七千 六百 五十四万 三千 二百 一十")
        XCTAssertEqual(simplified.read(251_5836_7200), "二百 五十一亿 五千 八百 三十六万 七千 二百")
        XCTAssertEqual(simplified.read(1234_5678_9012), "一千 二百 三十四亿 五千 六百 七十八万 九千 零一十二")
        XCTAssertEqual(simplified.read(6789_8765_4321), "六千 七百 八十九亿 八千 七百 六十五万 四千 三百 二十一")
        XCTAssertEqual(simplified.read(1_0000_0000_0000), "一兆")
    }
}
